// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: node/node.proto

package node

import (
	context "context"
	common "github.com/Layr-Labs/eigenda/api/grpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dispersal_StoreChunks_FullMethodName = "/node.Dispersal/StoreChunks"
	Dispersal_StoreBlobs_FullMethodName  = "/node.Dispersal/StoreBlobs"
	Dispersal_AttestBatch_FullMethodName = "/node.Dispersal/AttestBatch"
	Dispersal_NodeInfo_FullMethodName    = "/node.Dispersal/NodeInfo"
)

// DispersalClient is the client API for Dispersal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DispersalClient interface {
	// StoreChunks validates that the chunks match what the Node is supposed to receive (
	// different Nodes are responsible for different chunks, as EigenDA is horizontally
	// sharded) and is correctly coded (e.g. each chunk must be a valid KZG multiproof)
	// according to the EigenDA protocol. It also stores the chunks along with metadata
	// for the protocol-defined length of custody. It will return a signature at the
	// end to attest to the data in this request it has processed.
	StoreChunks(ctx context.Context, in *StoreChunksRequest, opts ...grpc.CallOption) (*StoreChunksReply, error)
	// StoreBlobs is simiar to StoreChunks, but it stores the blobs using a different storage schema
	// so that the stored blobs can later be aggregated by AttestBatch method to a bigger batch.
	// StoreBlobs + AttestBatch will eventually replace and deprecate StoreChunks method.
	StoreBlobs(ctx context.Context, in *StoreBlobsRequest, opts ...grpc.CallOption) (*StoreBlobsReply, error)
	// AttestBatch is used to aggregate the batches stored by StoreBlobs method to a bigger batch.
	// It will return a signature at the end to attest to the aggregated batch.
	AttestBatch(ctx context.Context, in *AttestBatchRequest, opts ...grpc.CallOption) (*AttestBatchReply, error)
	// Retrieve node info metadata
	NodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*NodeInfoReply, error)
}

type dispersalClient struct {
	cc grpc.ClientConnInterface
}

func NewDispersalClient(cc grpc.ClientConnInterface) DispersalClient {
	return &dispersalClient{cc}
}

func (c *dispersalClient) StoreChunks(ctx context.Context, in *StoreChunksRequest, opts ...grpc.CallOption) (*StoreChunksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreChunksReply)
	err := c.cc.Invoke(ctx, Dispersal_StoreChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispersalClient) StoreBlobs(ctx context.Context, in *StoreBlobsRequest, opts ...grpc.CallOption) (*StoreBlobsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreBlobsReply)
	err := c.cc.Invoke(ctx, Dispersal_StoreBlobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispersalClient) AttestBatch(ctx context.Context, in *AttestBatchRequest, opts ...grpc.CallOption) (*AttestBatchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestBatchReply)
	err := c.cc.Invoke(ctx, Dispersal_AttestBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispersalClient) NodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*NodeInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeInfoReply)
	err := c.cc.Invoke(ctx, Dispersal_NodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispersalServer is the server API for Dispersal service.
// All implementations must embed UnimplementedDispersalServer
// for forward compatibility.
type DispersalServer interface {
	// StoreChunks validates that the chunks match what the Node is supposed to receive (
	// different Nodes are responsible for different chunks, as EigenDA is horizontally
	// sharded) and is correctly coded (e.g. each chunk must be a valid KZG multiproof)
	// according to the EigenDA protocol. It also stores the chunks along with metadata
	// for the protocol-defined length of custody. It will return a signature at the
	// end to attest to the data in this request it has processed.
	StoreChunks(context.Context, *StoreChunksRequest) (*StoreChunksReply, error)
	// StoreBlobs is simiar to StoreChunks, but it stores the blobs using a different storage schema
	// so that the stored blobs can later be aggregated by AttestBatch method to a bigger batch.
	// StoreBlobs + AttestBatch will eventually replace and deprecate StoreChunks method.
	StoreBlobs(context.Context, *StoreBlobsRequest) (*StoreBlobsReply, error)
	// AttestBatch is used to aggregate the batches stored by StoreBlobs method to a bigger batch.
	// It will return a signature at the end to attest to the aggregated batch.
	AttestBatch(context.Context, *AttestBatchRequest) (*AttestBatchReply, error)
	// Retrieve node info metadata
	NodeInfo(context.Context, *NodeInfoRequest) (*NodeInfoReply, error)
	mustEmbedUnimplementedDispersalServer()
}

// UnimplementedDispersalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDispersalServer struct{}

func (UnimplementedDispersalServer) StoreChunks(context.Context, *StoreChunksRequest) (*StoreChunksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreChunks not implemented")
}
func (UnimplementedDispersalServer) StoreBlobs(context.Context, *StoreBlobsRequest) (*StoreBlobsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreBlobs not implemented")
}
func (UnimplementedDispersalServer) AttestBatch(context.Context, *AttestBatchRequest) (*AttestBatchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttestBatch not implemented")
}
func (UnimplementedDispersalServer) NodeInfo(context.Context, *NodeInfoRequest) (*NodeInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeInfo not implemented")
}
func (UnimplementedDispersalServer) mustEmbedUnimplementedDispersalServer() {}
func (UnimplementedDispersalServer) testEmbeddedByValue()                   {}

// UnsafeDispersalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispersalServer will
// result in compilation errors.
type UnsafeDispersalServer interface {
	mustEmbedUnimplementedDispersalServer()
}

func RegisterDispersalServer(s grpc.ServiceRegistrar, srv DispersalServer) {
	// If the following call pancis, it indicates UnimplementedDispersalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dispersal_ServiceDesc, srv)
}

func _Dispersal_StoreChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispersalServer).StoreChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispersal_StoreChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispersalServer).StoreChunks(ctx, req.(*StoreChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispersal_StoreBlobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreBlobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispersalServer).StoreBlobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispersal_StoreBlobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispersalServer).StoreBlobs(ctx, req.(*StoreBlobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispersal_AttestBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispersalServer).AttestBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispersal_AttestBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispersalServer).AttestBatch(ctx, req.(*AttestBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispersal_NodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispersalServer).NodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispersal_NodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispersalServer).NodeInfo(ctx, req.(*NodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dispersal_ServiceDesc is the grpc.ServiceDesc for Dispersal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dispersal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "node.Dispersal",
	HandlerType: (*DispersalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreChunks",
			Handler:    _Dispersal_StoreChunks_Handler,
		},
		{
			MethodName: "StoreBlobs",
			Handler:    _Dispersal_StoreBlobs_Handler,
		},
		{
			MethodName: "AttestBatch",
			Handler:    _Dispersal_AttestBatch_Handler,
		},
		{
			MethodName: "NodeInfo",
			Handler:    _Dispersal_NodeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node/node.proto",
}

const (
	Retrieval_RetrieveChunks_FullMethodName = "/node.Retrieval/RetrieveChunks"
	Retrieval_GetBlobHeader_FullMethodName  = "/node.Retrieval/GetBlobHeader"
	Retrieval_NodeInfo_FullMethodName       = "/node.Retrieval/NodeInfo"
	Retrieval_GetChunks_FullMethodName      = "/node.Retrieval/GetChunks"
	Retrieval_GetChunk_FullMethodName       = "/node.Retrieval/GetChunk"
	Retrieval_GetHeader_FullMethodName      = "/node.Retrieval/GetHeader"
	Retrieval_StreamHeaders_FullMethodName  = "/node.Retrieval/StreamHeaders"
	Retrieval_GetNodeInfo_FullMethodName    = "/node.Retrieval/GetNodeInfo"
)

// RetrievalClient is the client API for Retrieval service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RetrievalClient interface {
	// RetrieveChunks retrieves the chunks for a blob custodied at the Node.
	RetrieveChunks(ctx context.Context, in *RetrieveChunksRequest, opts ...grpc.CallOption) (*RetrieveChunksReply, error)
	// GetBlobHeader is similar to RetrieveChunks, this just returns the header of the blob.
	GetBlobHeader(ctx context.Context, in *GetBlobHeaderRequest, opts ...grpc.CallOption) (*GetBlobHeaderReply, error)
	// Retrieve node info metadata
	NodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*NodeInfoReply, error)
	// GetChunks retrieves all of the chunks from a specified quorum for a blob held by the node.
	// Eventually this will replace RetrieveChunks.
	GetChunks(ctx context.Context, in *GetChunksRequest, opts ...grpc.CallOption) (*GetChunksReply, error)
	// GetChunk retrieves a specific chunk for a blob custodied at the Node.
	GetChunk(ctx context.Context, in *common.ChunkKey, opts ...grpc.CallOption) (*common.ChunkData, error)
	// GetHeader is similar to RetrieveChunks, this just returns the header of the blob.
	// Eventually this will replace GetBlobHeader.
	GetHeader(ctx context.Context, in *common.BlobKey, opts ...grpc.CallOption) (*GetBlobHeaderReply, error)
	// StreamHeaders requests a stream all new headers.
	StreamHeaders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamHeadersRequest, GetBlobHeaderReply], error)
	// Retrieve node info metadata. Eventually this will replace NodeInfo.
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoReply, error)
}

type retrievalClient struct {
	cc grpc.ClientConnInterface
}

func NewRetrievalClient(cc grpc.ClientConnInterface) RetrievalClient {
	return &retrievalClient{cc}
}

func (c *retrievalClient) RetrieveChunks(ctx context.Context, in *RetrieveChunksRequest, opts ...grpc.CallOption) (*RetrieveChunksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveChunksReply)
	err := c.cc.Invoke(ctx, Retrieval_RetrieveChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalClient) GetBlobHeader(ctx context.Context, in *GetBlobHeaderRequest, opts ...grpc.CallOption) (*GetBlobHeaderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlobHeaderReply)
	err := c.cc.Invoke(ctx, Retrieval_GetBlobHeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalClient) NodeInfo(ctx context.Context, in *NodeInfoRequest, opts ...grpc.CallOption) (*NodeInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeInfoReply)
	err := c.cc.Invoke(ctx, Retrieval_NodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalClient) GetChunks(ctx context.Context, in *GetChunksRequest, opts ...grpc.CallOption) (*GetChunksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChunksReply)
	err := c.cc.Invoke(ctx, Retrieval_GetChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalClient) GetChunk(ctx context.Context, in *common.ChunkKey, opts ...grpc.CallOption) (*common.ChunkData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.ChunkData)
	err := c.cc.Invoke(ctx, Retrieval_GetChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalClient) GetHeader(ctx context.Context, in *common.BlobKey, opts ...grpc.CallOption) (*GetBlobHeaderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlobHeaderReply)
	err := c.cc.Invoke(ctx, Retrieval_GetHeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrievalClient) StreamHeaders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamHeadersRequest, GetBlobHeaderReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Retrieval_ServiceDesc.Streams[0], Retrieval_StreamHeaders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamHeadersRequest, GetBlobHeaderReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Retrieval_StreamHeadersClient = grpc.BidiStreamingClient[StreamHeadersRequest, GetBlobHeaderReply]

func (c *retrievalClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeInfoReply)
	err := c.cc.Invoke(ctx, Retrieval_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RetrievalServer is the server API for Retrieval service.
// All implementations must embed UnimplementedRetrievalServer
// for forward compatibility.
type RetrievalServer interface {
	// RetrieveChunks retrieves the chunks for a blob custodied at the Node.
	RetrieveChunks(context.Context, *RetrieveChunksRequest) (*RetrieveChunksReply, error)
	// GetBlobHeader is similar to RetrieveChunks, this just returns the header of the blob.
	GetBlobHeader(context.Context, *GetBlobHeaderRequest) (*GetBlobHeaderReply, error)
	// Retrieve node info metadata
	NodeInfo(context.Context, *NodeInfoRequest) (*NodeInfoReply, error)
	// GetChunks retrieves all of the chunks from a specified quorum for a blob held by the node.
	// Eventually this will replace RetrieveChunks.
	GetChunks(context.Context, *GetChunksRequest) (*GetChunksReply, error)
	// GetChunk retrieves a specific chunk for a blob custodied at the Node.
	GetChunk(context.Context, *common.ChunkKey) (*common.ChunkData, error)
	// GetHeader is similar to RetrieveChunks, this just returns the header of the blob.
	// Eventually this will replace GetBlobHeader.
	GetHeader(context.Context, *common.BlobKey) (*GetBlobHeaderReply, error)
	// StreamHeaders requests a stream all new headers.
	StreamHeaders(grpc.BidiStreamingServer[StreamHeadersRequest, GetBlobHeaderReply]) error
	// Retrieve node info metadata. Eventually this will replace NodeInfo.
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoReply, error)
	mustEmbedUnimplementedRetrievalServer()
}

// UnimplementedRetrievalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRetrievalServer struct{}

func (UnimplementedRetrievalServer) RetrieveChunks(context.Context, *RetrieveChunksRequest) (*RetrieveChunksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveChunks not implemented")
}
func (UnimplementedRetrievalServer) GetBlobHeader(context.Context, *GetBlobHeaderRequest) (*GetBlobHeaderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlobHeader not implemented")
}
func (UnimplementedRetrievalServer) NodeInfo(context.Context, *NodeInfoRequest) (*NodeInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeInfo not implemented")
}
func (UnimplementedRetrievalServer) GetChunks(context.Context, *GetChunksRequest) (*GetChunksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChunks not implemented")
}
func (UnimplementedRetrievalServer) GetChunk(context.Context, *common.ChunkKey) (*common.ChunkData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChunk not implemented")
}
func (UnimplementedRetrievalServer) GetHeader(context.Context, *common.BlobKey) (*GetBlobHeaderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHeader not implemented")
}
func (UnimplementedRetrievalServer) StreamHeaders(grpc.BidiStreamingServer[StreamHeadersRequest, GetBlobHeaderReply]) error {
	return status.Errorf(codes.Unimplemented, "method StreamHeaders not implemented")
}
func (UnimplementedRetrievalServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedRetrievalServer) mustEmbedUnimplementedRetrievalServer() {}
func (UnimplementedRetrievalServer) testEmbeddedByValue()                   {}

// UnsafeRetrievalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RetrievalServer will
// result in compilation errors.
type UnsafeRetrievalServer interface {
	mustEmbedUnimplementedRetrievalServer()
}

func RegisterRetrievalServer(s grpc.ServiceRegistrar, srv RetrievalServer) {
	// If the following call pancis, it indicates UnimplementedRetrievalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Retrieval_ServiceDesc, srv)
}

func _Retrieval_RetrieveChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServer).RetrieveChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Retrieval_RetrieveChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServer).RetrieveChunks(ctx, req.(*RetrieveChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Retrieval_GetBlobHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlobHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServer).GetBlobHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Retrieval_GetBlobHeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServer).GetBlobHeader(ctx, req.(*GetBlobHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Retrieval_NodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServer).NodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Retrieval_NodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServer).NodeInfo(ctx, req.(*NodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Retrieval_GetChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServer).GetChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Retrieval_GetChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServer).GetChunks(ctx, req.(*GetChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Retrieval_GetChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.ChunkKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServer).GetChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Retrieval_GetChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServer).GetChunk(ctx, req.(*common.ChunkKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Retrieval_GetHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.BlobKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServer).GetHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Retrieval_GetHeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServer).GetHeader(ctx, req.(*common.BlobKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Retrieval_StreamHeaders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RetrievalServer).StreamHeaders(&grpc.GenericServerStream[StreamHeadersRequest, GetBlobHeaderReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Retrieval_StreamHeadersServer = grpc.BidiStreamingServer[StreamHeadersRequest, GetBlobHeaderReply]

func _Retrieval_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Retrieval_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Retrieval_ServiceDesc is the grpc.ServiceDesc for Retrieval service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Retrieval_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "node.Retrieval",
	HandlerType: (*RetrievalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveChunks",
			Handler:    _Retrieval_RetrieveChunks_Handler,
		},
		{
			MethodName: "GetBlobHeader",
			Handler:    _Retrieval_GetBlobHeader_Handler,
		},
		{
			MethodName: "NodeInfo",
			Handler:    _Retrieval_NodeInfo_Handler,
		},
		{
			MethodName: "GetChunks",
			Handler:    _Retrieval_GetChunks_Handler,
		},
		{
			MethodName: "GetChunk",
			Handler:    _Retrieval_GetChunk_Handler,
		},
		{
			MethodName: "GetHeader",
			Handler:    _Retrieval_GetHeader_Handler,
		},
		{
			MethodName: "GetNodeInfo",
			Handler:    _Retrieval_GetNodeInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHeaders",
			Handler:       _Retrieval_StreamHeaders_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "node/node.proto",
}
