// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Layr-Labs/eigenda/api/grpc/controller (interfaces: ControllerServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_controller_service_client.go -package=mocks github.com/Layr-Labs/eigenda/api/grpc/controller ControllerServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	controller "github.com/Layr-Labs/eigenda/api/grpc/controller"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockControllerServiceClient is a mock of ControllerServiceClient interface.
type MockControllerServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockControllerServiceClientMockRecorder
	isgomock struct{}
}

// MockControllerServiceClientMockRecorder is the mock recorder for MockControllerServiceClient.
type MockControllerServiceClientMockRecorder struct {
	mock *MockControllerServiceClient
}

// NewMockControllerServiceClient creates a new mock instance.
func NewMockControllerServiceClient(ctrl *gomock.Controller) *MockControllerServiceClient {
	mock := &MockControllerServiceClient{ctrl: ctrl}
	mock.recorder = &MockControllerServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerServiceClient) EXPECT() *MockControllerServiceClientMockRecorder {
	return m.recorder
}

// AuthorizePayment mocks base method.
func (m *MockControllerServiceClient) AuthorizePayment(ctx context.Context, in *controller.AuthorizePaymentRequest, opts ...grpc.CallOption) (*controller.AuthorizePaymentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AuthorizePayment", varargs...)
	ret0, _ := ret[0].(*controller.AuthorizePaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizePayment indicates an expected call of AuthorizePayment.
func (mr *MockControllerServiceClientMockRecorder) AuthorizePayment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizePayment", reflect.TypeOf((*MockControllerServiceClient)(nil).AuthorizePayment), varargs...)
}
