[profile.default]
src = 'EigenDAServiceManager/src'
out = 'out'
libs = ['lib']

# Compilation settings from Etherscan
solc_version = '0.8.12'
optimizer = true
optimizer_runs = 200
evm_version = 'london'

# Comprehensive remappings for complex structure
remappings = [
  "@openzeppelin-upgrades/=EigenDAServiceManager/lib/openzeppelin-contracts-upgradeable/",
  "@openzeppelin/=EigenDAServiceManager/lib/openzeppelin-contracts/",
  "eigenlayer-contracts/=EigenDAServiceManager/lib/eigenlayer-middleware/lib/eigenlayer-contracts/",
  "eigenlayer-core/=EigenDAServiceManager/lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/",
  "eigenlayer-middleware/=EigenDAServiceManager/lib/eigenlayer-middleware/src/"
]
