version: "2"

run:
  # CI was timing out with the default timeout of 1m.
  timeout: 5m

linters:
  enable:
    - protogetter # reports direct reads from proto message fields when getters should be used.
    - revive # drop-in replacement for golint

issues:
  # Only show issues in new/modified code, not existing code
  new: true
  # Diff compared to master will be linted by default, but the --new-from-rev= flag can be used when running the linter
  # to lint the diff between the feature and a different target. This is how CI handles the linting: it lints the diff
  # between the feature branch, and the branch being merged into.
  new-from-rev: master
