version: "2"

run:
  # CI was timing out with the default timeout of 1m.
  timeout: 5m

linters:
  enable:
    - protogetter # reports direct reads from proto message fields when getters should be used.
    - revive # drop-in replacement for golint

issues:
  # Only show issues in new/modified code, not existing code
  new: true
  new-from-rev: master
