version: "2"

run:
  # CI was timing out with the default timeout of 1m.
  timeout: 5m

linters:
  enable:
    - protogetter # reports direct reads from proto message fields when getters should be used
    - revive      # drop-in replacement for golint
    - lll         # enforces line length limits
    - errorlint   # makes sure errors are wrapped correctly
    - misspell    # checks for common misspellings
    - funlen      # limits function length
    - nestif      # limits nesting depth
    - exhaustive  # makes sure enum switch statements are exhaustive
    - errcheck    # enforces that all errors are checked
    - unused      # checks for unused constants, variables, functions and types
    - unconvert   # removes unnecessary type conversions
    - wrapcheck   # checks that errors returned from external packages are wrapped
    - govet       # reports suspicious constructs

linters-settings:
  lll:
    line-length: 120
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck # prevents "foo.Foo" style warnings
  errorlint:
    # Check whether fmt.Errorf uses the %w verb for formatting errors
    errorf: true

issues:
  include:
    - EXC0012 # enable default-disabled revive rule: exported items should have a comment

  # Allow certain patterns to be ignored by lll (long lines)
  # This should probably be 120 to match our lll rule, but there is a weird interaction which an external contributor
  # hit. The bug was a string smaller than 120, but with key + string made the line bigger than 120, which invalidated
  # the exclusion rule.
  exclude-rules:
    - source: '".{100,}"' # ignores double-quoted strings longer than 100 chars
      linters: [lll]
    - source: "// https?://" # pattern matches comments containing URLs
      linters: [lll]
  
  # Only show issues in new/modified code, not existing code
  new: true
  # Diff compared to origin/master will be linted by default, but the --new-from-rev= flag can be used when running the linter
  # to lint the diff between the feature and a different target. This is how CI handles the linting: it lints the diff
  # between the feature branch, and the branch being merged into.
  new-from-rev: origin/master
