version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

git:
  tag_sort: -version:creatordate

builds:
  - id: node
    main: ./node/cmd/main.go
    binary: node
    flags:
      - -v
    ldflags:
      - -X 'github.com/Layr-Labs/eigenda/node.SemVer={{ .Version }}'
      - -X 'github.com/Layr-Labs/eigenda/node.GitCommit={{ .ShortCommit }}'
      - -X 'github.com/Layr-Labs/eigenda/node.Arch={{ .Arch }}'
      - -X 'github.com/Layr-Labs/eigenda/node.Os={{ .Os }}'
      - -X 'github.com/Layr-Labs/eigenda/node.GitDate={{ .Timestamp }}'
    # contains linux and darwin
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: node_plugin
    main: ./node/plugin/cmd/main.go
    binary: node_plugin
    flags:
      - -v
    ldflags:
      - -X 'github.com/Layr-Labs/eigenda/node.SemVer={{ .Version }}'
      - -X 'github.com/Layr-Labs/eigenda/node.GitCommit={{ .ShortCommit }}'
      - -X 'github.com/Layr-Labs/eigenda/node.Arch={{ .Arch }}'
      - -X 'github.com/Layr-Labs/eigenda/node.Os={{ .Os }}'
      - -X 'github.com/Layr-Labs/eigenda/node.GitDate={{ .Timestamp }}'
    # contains linux and darwin
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-node:{{ .Version }}'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-node:latest'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--target=node"
      - "--build-arg=SEMVER={{ .Version }}"
      - "--build-arg=GITCOMMIT={{ .ShortCommit }}"
      - "--build-arg=GITDATE={{ .Timestamp }}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    ids:
      - node
  - image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-node:{{ .Version }}-arm64'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--target=node"
      - "--build-arg=SEMVER={{ .Version }}"
      - "--build-arg=GITCOMMIT={{ .ShortCommit }}"
      - "--build-arg=GITDATE={{ .Timestamp }}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    ids:
      - node
  - image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-nodeplugin:{{ .Version }}'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-nodeplugin:latest'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--target=nodeplugin"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    ids:
      - node_plugin
  - image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-nodeplugin:{{ .Version }}-arm64'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--target=nodeplugin"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    ids:
      - node_plugin

docker_manifests:
  - name_template: 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-node:{{ .Version }}'
    image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-node:{{ .Version }}'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-node:{{ .Version }}-arm64'
  - name_template: 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-node:latest'
    image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-node:latest'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-node:{{ .Version }}-arm64'
  - name_template: 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-nodeplugin:{{ .Version }}'
    image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-nodeplugin:{{ .Version }}'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-nodeplugin:{{ .Version }}-arm64'
  - name_template: 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-nodeplugin:latest'
    image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-nodeplugin:latest'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | default "pschork" }}/eigenda/opr-nodeplugin:{{ .Version }}-arm64'

release:
  github:
    owner: pschork
    name: eigenda

  draft: true

archives:
  - formats: [ 'tar.gz' ]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
