# This file is used for building and pushing images
services:
  node:
    build:
      context: .
      dockerfile: node/cmd/Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: ghcr.io/layr-labs/eigenda/opr-node:${RELEASE_TAG}
  nodeplugin:
    build:
      context: .
      dockerfile: node/plugin/cmd/Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: ghcr.io/layr-labs/eigenda/opr-nodeplugin:${RELEASE_TAG}
