.PHONY: compile-el compile-dl clean protoc mdbook-serve lint build unit-tests integration-tests-churner integration-tests-indexer integration-tests-inabox integration-tests-inabox-nochurner integration-tests-graph-indexer check-fmt

ifeq ($(wildcard .git/*),)
$(warning semver disabled - building from release zip)
GITCOMMIT := ""
GITSHA := ""
GITDATE := ""
BRANCH := ""
SEMVER := $(shell basename $(CURDIR))
else
GITCOMMIT := $(shell git rev-parse --short HEAD)
GITDATE := $(shell git log -1 --format=%cd --date=unix)
GITSHA := $(shell git rev-parse HEAD)
BRANCH := $(shell git rev-parse --abbrev-ref HEAD | sed 's/[^[:alnum:]\.\_\-]/-/g')
SEMVER := $(shell docker run --rm --volume "$(PWD):/repo" gittools/gitversion:5.12.0 /repo -output json -showvariable SemVer)
ifeq ($(SEMVER), )
$(warning semver disabled - docker not installed)
SEMVER := "0.0.0"
endif
endif

RELEASE_TAG := $(or $(RELEASE_TAG),latest)

compile-contracts:
	$(MAKE) -C contracts compile

clean:
	$(MAKE) -C api clean

# Builds the protobuf files inside a docker container.
protoc:
	$(MAKE) -C api protoc

# Builds the protobuf files locally (i.e. without docker).
protoc-local:
	$(MAKE) -C api protoc-local

lint:
	golangci-lint run
	go vet ./...
	# Uncomment this once we update to go1.23 which makes the -diff flag available.
	# See https://tip.golang.org/doc/go1.23#go-command
	# go mod tidy -diff
	$(MAKE) -C api/proxy lint


# TODO: this should also format github workflows, etc.
fmt:
	$(MAKE) -C contracts fmt
	go fmt ./...

# TODO: this should also check github workflows, etc.
fmt-check:
	$(MAKE) -C contracts fmt-check
	# go list template was generated by Claude. I didn't double check that it expands to the exact
	# same files as `go fmt ./...`, but it should be equivalent.
	output=$$(gofmt -l $$(go list -f '{{range .GoFiles}}{{$$.Dir}}/{{.}} {{end}}' ./...)); \
	if [ -n "$$output" ]; then \
		echo "Files not gofmt'd:"; \
		echo "$$output"; \
		exit 1; \
	fi

# Go's VCS stamping logic assumes .git is always a directory, but in worktrees it's a file.
# This causes "error obtaining VCS status" when building because Go can't parse the file format.
# See https://github.com/golang/go/issues/58218#issuecomment-1471302281
#
# So we detect if we're in a git worktree (where .git is a file, not a directory)
# and set GOFLAGS to disable VCS stamping to avoid build errors if so.
# This is a temporary workaround until Go's VCS handling is fixed.
ifeq ($(shell test -f .git && echo "true"),true)
export GOFLAGS := -buildvcs=false
$(warning Detected git worktree - disabling VCS stamping)
endif
build:
	cd operators/churner && make build
	cd disperser && make build
	cd node && make build
	cd retriever && make build
	cd tools/traffic && make build
	cd tools/kzgpad && make build
	cd relay && make build
	cd litt && make build

dataapi-build:
	cd disperser && go build -o ./bin/dataapi ./cmd/dataapi

unit-tests:
	./test.sh

live-tests:
	go test -v ./test/v2/live -v -timeout 60m
live-tests-v1:
	go test -v ./api/clients --live-test

fuzz-tests:
	go test --fuzz=FuzzParseSignatureKMS -fuzztime=5m ./common

integration-tests-churner:
	go test -v ./churner/tests

integration-tests-indexer:
	go test -v ./core/indexer

integration-tests-node-plugin:
	go test -v ./node/plugin/tests

integration-tests-inabox:
	make build
	cd inabox && make run-e2e

integration-tests-inabox-nochurner:
	make build
	cd inabox && make run-e2e-nochurner

integration-tests-graph-indexer:
	make build
	go test -v ./core/thegraph

integration-tests-dataapi:
	make dataapi-build
	go test -v ./disperser/dataapi

# builds all services and loads them into dockerd (such that they are available via `docker images`).
# The images will be tagged with :dev, which is the default BUILD_TAG in docker-bake.hcl.
# This can be changed by running for example `BUILD_TAG=master make docker-build`.
docker-build:
	docker buildx bake all --load

# builds all services and pushes them to the configured registry (ghcr by default).
docker-build-push:
	docker buildx bake all --push

# Should only ever be used by the docker-publish-release CI workflow.
# We keep the node-group and proxy targets separate since we might want to release them separately in the future.
docker-release-build:
	BUILD_TAG=${SEMVER} SEMVER=${SEMVER} GITDATE=${GITDATE} GIT_SHA=${GITSHA} GIT_SHORT_SHA=${GITCOMMIT} \
	docker buildx bake node-group-release ${PUSH_FLAG}
	BUILD_TAG=${SEMVER} SEMVER=${SEMVER} GITDATE=${GITDATE} GIT_SHA=${GITSHA} GIT_SHORT_SHA=${GITCOMMIT} \
	docker buildx bake proxy-release ${PUSH_FLAG}

semver:
	echo "${SEMVER}"

##### Proxies to other local Makefiles #####
mdbook-serve:
	$(MAKE) -C docs/spec serve