.PHONY: compile-el compile-dl clean protoc mdbook-serve lint build unit-tests integration-tests integration-tests-churner integration-tests-indexer integration-tests-node-plugin integration-tests-eigenda-client integration-tests-inabox integration-tests-inabox-nochurner integration-tests-graph-indexer integration-tests-dataapi check-fmt

ifeq ($(wildcard .git/*),)
$(warning semver disabled - building from release zip)
GITCOMMIT := ""
GITSHA := ""
GITDATE := ""
BRANCH := ""
SEMVER := $(shell basename $(CURDIR))
else
GITCOMMIT := $(shell git rev-parse --short HEAD)
GITDATE := $(shell git log -1 --format=%cd --date=unix)
GITSHA := $(shell git rev-parse HEAD)
BRANCH := $(shell git rev-parse --abbrev-ref HEAD | sed 's/[^[:alnum:]\.\_\-]/-/g')
SEMVER := $(shell docker run --rm --volume "$(PWD):/repo" gittools/gitversion:5.12.0 /repo -output json -showvariable SemVer)
ifeq ($(SEMVER), )
$(warning semver disabled - docker not installed)
SEMVER := "0.0.0"
endif
endif

RELEASE_TAG := $(or $(RELEASE_TAG),latest)

compile-contracts:
	$(MAKE) -C contracts compile

clean:
	$(MAKE) -C api clean

# Builds the protobuf files inside a docker container.
protoc:
	$(MAKE) -C api protoc

# Builds the protobuf files locally (i.e. without docker).
protoc-local:
	$(MAKE) -C api protoc-local

lint:
	golangci-lint run
	go vet ./...
	# Uncomment this once we update to go1.23 which makes the -diff flag available.
	# See https://tip.golang.org/doc/go1.23#go-command
	# go mod tidy -diff


# TODO: this should also format github workflows, etc.
fmt:
	$(MAKE) -C contracts fmt
	go fmt ./...

# TODO: this should also check github workflows, etc.
fmt-check:
	$(MAKE) -C contracts fmt-check
	# go list template was generated by Claude. I didn't double check that it expands to the exact
	# same files as `go fmt ./...`, but it should be equivalent.
	output=$$(gofmt -l $$(go list -f '{{range .GoFiles}}{{$$.Dir}}/{{.}} {{end}}' ./...)); \
	if [ -n "$$output" ]; then \
		echo "Files not gofmt'd:"; \
		echo "$$output"; \
		exit 1; \
	fi

build:
	cd operators/churner && make build
	cd disperser && make build
	cd node && make build
	cd retriever && make build
	cd tools/traffic && make build
	cd tools/kzgpad && make build
	cd relay && make build
	cd litt && make build

docker-release-build:
	BUILD_TAG=${SEMVER} SEMVER=${SEMVER} GITDATE=${GITDATE} GIT_SHA=${GITSHA} GIT_SHORT_SHA=${GITCOMMIT} \
	docker buildx bake node-group-release ${PUSH_FLAG}
	BUILD_TAG=${SEMVER} SEMVER=${SEMVER} GITDATE=${GITDATE} GIT_SHA=${GITSHA} GIT_SHORT_SHA=${GITCOMMIT} \
	docker buildx bake proxy ${PUSH_FLAG}

# Some of the unit test suites take > 1 min to run (e.g. relay and littdb tests).
# TODO: we should break these up into short and long unit-tests.
unit-tests:
	./test.sh

fuzz-tests:
	go test --fuzz=FuzzParseSignatureKMS -fuzztime=5m ./common

# Integration tests use mocks
integration-tests:
	go test -v ./churner/tests
	go test -v ./core/indexer
	go test -v ./node/plugin/tests
# TODO: this test is against holesky, should be moved to the live-tests.
	go test -v ./api/clients --testnet-integration
	go test -v ./disperser/dataapi

# Tests that require a build because they start local inabox infra:
# either chain, subgraph, or localstack.
integration-tests-inabox: build
	cd inabox && make run-e2e
	go test -v ./core/thegraph

# These are e2e tests that run against live environments (preprod and holesky currently).
live-tests:
	go test -v ./test/v2/live -v -timeout 60m

semver:
	echo "${SEMVER}"

##### Proxies to other local Makefiles #####
mdbook-serve:
	$(MAKE) -C docs/spec serve