// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import {EigenDATypesV1 as DATypesV1} from "src/core/libraries/v1/EigenDATypesV1.sol";
import {EigenDACertTypes} from "src/periphery/cert/EigenDACertTypes.sol";

/// @dev The EigenDA team requires ABIs for EigenDA certificate types.
///      However, ABIs for types are not generated by the solidity compiler without a function defined.
///      This interface is simply a workaround for this limitation.
interface IEigenDACertTypeBindings {
    function dummyVerifyDACertV1(
        DATypesV1.BlobHeader calldata blobHeader,
        DATypesV1.BlobVerificationProof calldata blobVerificationProof
    ) external view;

    // There is no need for a V2 dummy because the V2 types are available in the V3 cert.

    function dummyVerifyDACertV3(EigenDACertTypes.EigenDACertV3 memory cert) external view;
}
