// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import {EigenDACertTypes} from "src/periphery/cert/EigenDACertTypes.sol";

/// @dev The EigenDA team requires ABIs for EigenDA certificate types.
///      However, ABIs for types are not generated by the solidity compiler without a function defined.
///      This interface is simply a workound for this limitation.
interface IEigenDACertTypeBindings {
    function dummyFnCertV3(EigenDACertTypes.EigenDACertV3 memory cert) external view;
}
