{
 "title": "EigenDA",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rank by TVL in Quorums",
   "type": "stat",
   "description": "1 being the highest.\n\n0 - you are not opted in that quorum",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_registered_quorums_rank", "legendFormat": "quorum {{quorum}}" }
   ]
  },
  {
   "title": "Stake Share in Quorums (In Basis Points)",
   "type": "timeseries",
   "description": "Divide by 100 to get %age stake.\n\n0 for a quorum means you are opted out of that quorum",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "node_registered_quorums_stake_share",
     "legendFormat": "quorum {{quorum}}"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "stat",
   "description": "Display reachability status of the node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_reachability_status", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Total Socket updates",
   "type": "stat",
   "description": "the total number of node's socket address updates",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_eigenda_node_socket_updates_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "V1 Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Signing Rate",
   "type": "timeseries",
   "description": "Number of signed / Number of received batches\nThis metrics doesn't account for batches you did not receive due to any connectivity issues",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A * 100 / $B", "type": "math" }
   ]
  },
  {
   "title": "Average processed batch size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_eigenda_processed_batches_total{type=\"size\"})\n/\nsum(node_eigenda_processed_batches_total{type=\"number\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch by status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (node_eigenda_processed_batches_total{type=\"number\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EigenDA number of processed batches",
   "type": "timeseries",
   "description": "the total number of batches processed by the DA node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "node_eigenda_processed_batches_total{type=\"number\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "EigenDA size of processed batches",
   "type": "timeseries",
   "description": "the total size of batches processed by the DA node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_eigenda_processed_batches_total{type=\"size\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of EigenDA Blobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "node_eigenda_blobs_total{type=\"number\"}",
     "legendFormat": "quorum {{quorum}}"
    }
   ]
  },
  {
   "title": "Size of EigenDA Blobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_eigenda_blobs_total{type=\"size\"}",
     "legendFormat": "quorum {{quorum}}"
    }
   ]
  },
  {
   "title": "EigenDA StoreChunks RPC rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(node_eigenda_rpc_requests_total{method=\"StoreChunks\"}[$__range])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request Latency StoreChunks (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "node_request_latency_ms{quantile=\"0.99\", method=\"StoreChunks\"}",
     "legendFormat": "p99 {{stage}}"
    },
    {
     "expr": "node_request_latency_ms{quantile=\"0.95\", method=\"StoreChunks\"}",
     "legendFormat": "p95 {{stage}}"
    }
   ]
  },
  {
   "title": "EigenDA size of removed batches",
   "type": "timeseries",
   "description": "the total size of batches that have been removed by the DA node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "node_eigenda_processed_batches_total{type=\"size\", status=\"removed\"} / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EigenDA number of removed batches",
   "type": "timeseries",
   "description": "the total number  of batches that have been removed by the DA node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "node_eigenda_removed_batches_total{type=\"number\", status=\"removed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "V2 Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "EigenDA V2 RPC Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(grpc_server_started_total{grpc_service=~\"validator.(Dispersal|Retrieval)\"}[3m])",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "EigenDA V2 Store Chunks Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(eigenda_node_store_chunks_request_size_bytes{ })",
     "legendFormat": "Store Chunks"
    }
   ]
  },
  {
   "title": "EigenDA V2 RPC Success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_service=~\"validator.(Dispersal|Retrieval)\", grpc_code=\"OK\"}[3m])",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "EigenDA V2 RPC Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{grpc_service=~\"validator.(Dispersal|Retrieval)\", grpc_code=\"Internal\"}[3m])",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "EigenDA V2 Average Store Chunks Latency by Stage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  sum by (stage) (\n    rate(\n      eigenda_node_store_chunks_stage_latency_ms_sum{}[5m]\n    )\n  )\n)\n/\n(\n  sum by (stage) (\n    rate(\n      eigenda_node_store_chunks_stage_latency_ms_count{}[5m]\n    )\n  )\n)\n",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "EigenDA V2 Store Chunks p50 Latency By Stage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (stage) (\n    eigenda_node_store_chunks_stage_latency_ms{\n      quantile=\"0.5\"\n    }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EigenDA V2 Store Chunks p90 Latency By Stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (stage) (\n    eigenda_node_store_chunks_stage_latency_ms{\n      quantile=\"0.9\"\n    }\n)\n",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "EigenDA V2 Store Chunks p99 Latency By Stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (stage) (\n    eigenda_node_store_chunks_stage_latency_ms{\n      quantile=\"0.99\"\n    }\n)\n",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "EigenDA V2 Get Chunks Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(eigenda_node_get_chunks_latency_ms{\n}) by (quantile)",
     "legendFormat": "p{{quantile}}"
    }
   ]
  },
  { "title": "LittDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Disk Footprint",
   "type": "timeseries",
   "description": "Size of LittDB data on disk.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_littdb_table_size_bytes{})\n",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Read Cache Size",
   "type": "timeseries",
   "description": "The memory footprint of the read cache.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_littdb_chunk_read_cache_weight{})\n",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Write Cache Size",
   "type": "timeseries",
   "description": "The memory footprint of the write cache.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_littdb_chunk_write_cache_weight{})\n",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "Bytes Read / Second",
   "type": "timeseries",
   "description": "Rate of bytes read from LittDB",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(rate(node_littdb_bytes_read{}[3m])) by (service)",
     "legendFormat": "reads"
    }
   ]
  },
  {
   "title": "Bytes Written / Second",
   "type": "timeseries",
   "description": "Rate of bytes written to LittDB",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(rate(node_littdb_bytes_written{}[3m])) by (service)",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "description": "The average latency of LittDB read operations.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(node_littdb_read_latency_ms{}) by (quantile)\n",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(rate(node_littdb_read_latency_ms_sum{}[5m]))\n/\nsum(rate(node_littdb_read_latency_ms_count{}[5m]))\n",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "description": "The average latency of LittDB write operations.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(node_littdb_write_latency_ms{}) by (quantile)\n",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "sum(rate(node_littdb_write_latency_ms{}[5m]))\n/\nsum(rate(node_littdb_write_latency_ms_count{}[5m]))\n",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "description": "Rate of cache hits per second.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(node_littdb_cache_hits{}[5m]))\n",
     "legendFormat": "hits"
    }
   ]
  }
 ]
}