[profile.default]
src = 'IndexRegistry'
out = 'out'
libs = ['lib']

# Compilation settings from Etherscan
solc_version = '0.8.12'
optimizer = true
optimizer_runs = 200
evm_version = 'london'

# You may need to customize these remappings
remappings = [
  "@openzeppelin-upgrades/=IndexRegistry/lib/openzeppelin-contracts-upgradeable/",
  "@openzeppelin/=IndexRegistry/lib/openzeppelin-contracts/",
  "eigenlayer-middleware/=IndexRegistry/lib/eigenlayer-middleware/src/",
  "eigenlayer-core/=IndexRegistry/lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/",
  "eigenlayer-contracts/=IndexRegistry/lib/eigenlayer-middleware/lib/eigenlayer-contracts/"
]
