# This file contains the configuration for deploying the EigenDA Directory contract.
addressConfigs = [
    [
        { 0_name = "EXAMPLE", 1_address = "0xfC4C575ea3f8316D38F83076Cf765f7B8DeaFC58" },
        { 0_name = "EXAMPLE2", 1_address = "0xF2d1511E53AeAE16213EcA7963A103cB5CEc2b18" }
    ]
]

# The address of the proxy admin contract that manages the upgradeability of the contracts.
proxyAdmin = "0x9Fd7E279f5bD692Dc04792151E14Ad814FC60eC1"

# The privileged account that can manage the contract directory.
owner = "0xDA29BB71669f46F2a779b4b62f03644A84eE3479"