
# This field should be populated with the contract names for use in contract lookups.
contractNames = [
    "PAUSER_REGISTRY", 
    "BLS_APK_REGISTRY", 
    "INDEX_REGISTRY", 
    "STAKE_REGISTRY", 
    "SOCKET_REGISTRY", 
    "REGISTRY_COORDINATOR",
    "EJECTION_MANAGER", 
    "SERVICE_MANAGER",
    "OPERATOR_STATE_RETRIEVER",
    "THRESHOLD_REGISTRY",
    "RELAY_REGISTRY",
    "DISPERSER_REGISTRY",
    "PAYMENT_VAULT",
    "CERT_VERIFIER",
    "CERT_VERIFIER_LEGACY_V2"
]

# This field should be populated with the addresses of the contracts in the same order as in contractNames.
contractAddresses = [
    "0x748c7C573f64d79885CbdEaDB6D01f1ac977B0DF", # PAUSER_REGISTRY
    "0xb1B31663F9Bf4029C02a49A7813Aaf54c4AC91C9", # BLS_APK_REGISTRY
    "0x9b09da6AFC8179fAC9DE80f48bA449028aa055fF", # INDEX_REGISTRY
    "0xD4E4de4e80CbEc8d67cb9468715Ebf80c552be2a", # STAKE_REGISTRY
    "0xC50c9C440046B51Be7b0ABc24fC1FaA6Bc792a8E", # SOCKET_REGISTRY
    "0x964D17902e950281eAED56e162faD05510A5E4B6", # REGISTRY_COORDINATOR
    "0x6c50a60456576a009Aa27a6f171115Ca75428908", # EJECTION_MANAGER
    "0xd314209cE0ae9aDfD7643BB9d8becD62290D826a", # SERVICE_MANAGER
    "0x9E874193D8d500371bE151f2Bb8512Fc48a1f5aa", # OPERATOR_STATE_RETRIEVER
    "0xeC14d6045c9253b097fA040f70B696C6745B8835", # THRESHOLD_REGISTRY
    "0xe7a2FFdF33C61f7C256Dcdf786e066cdF9c98824", # RELAY_REGISTRY
    "0xE03c6623dC818c67e197F7C641AE678061835E9d", # DISPERSER_REGISTRY
    "0x4d2C6a77f96760363D1c0FD47fe269952A94f713", # PAYMENT_VAULT
    "0xD657303196621D50e430D30AcFb4eA8A781A928e", # CERT_VERIFIER
    "0x9D901Ea8971287294b417277c6176fE8172Fec6F", # CERT_VERIFIER_LEGACY_V2
]

# The address of the proxy admin contract that manages the upgradeability of the contracts.
proxyAdmin = "0x21c86AcC996489513F9CBa81fdea22F6c283D19b"

# The privileged account that can manage the contract directory.
owner = "0x002721B4790d97dC140a049936aA710152Ba92D5"