
# This field should be populated with the contract names for use in contract lookups.
contractNames = [
    "PAUSER_REGISTRY", 
    "BLS_APK_REGISTRY", 
    "INDEX_REGISTRY", 
    "STAKE_REGISTRY", 
    "SOCKET_REGISTRY", 
    "REGISTRY_COORDINATOR",
    "EJECTION_MANAGER", 
    "SERVICE_MANAGER",
    "OPERATOR_STATE_RETRIEVER",
    "THRESHOLD_REGISTRY",
    "RELAY_REGISTRY",
    "DISPERSER_REGISTRY",
    "PAYMENT_VAULT",
    "CERT_VERIFIER",
    "CERT_VERIFIER_V1",
    "CERT_VERIFIER_V2"
]

# This field should be populated with the addresses of the contracts in the same order as in contractNames.
contractAddresses = [
    "0x7e944db98Ad11b8010c123beF4330D859C90cafe", # PAUSER_REGISTRY
    "0xA8fF891E5b8cA255A0e884129bc14977F7A742BC", # BLS_APK_REGISTRY
    "0xE42Da83ddff0F1864F0d1F6d0d69ad066635DDFC", # INDEX_REGISTRY
    "0x2743FaA0df103f7c6D5c339f85c8eE51147C462e", # STAKE_REGISTRY
    "0x61Bc357f044da9c4323BeAD52834aEb1aA53ad05", # SOCKET_REGISTRY
    "0xAF21d3811B5d23D5466AC83BA7a9c34c261A8D81", # REGISTRY_COORDINATOR
    "0xc9d4541C409f15C0408c022D7e8C3F37Ac960f66", # EJECTION_MANAGER
    "0x3a5acf46ba6890B8536420F4900AC9BC45Df4764", # SERVICE_MANAGER
    "0x22478d082E9edaDc2baE8443E4aC9473F6E047Ff", # OPERATOR_STATE_RETRIEVER
    "0x0DA66C1930Acc54809093Bb42f2e6a4bE21d5403", # THRESHOLD_REGISTRY
    "0x10257B380cd6D106D982F1C3d63426DD3D3D769D", # RELAY_REGISTRY
    "0x851C8dCecA1552375EbB7010d90d51ddf6f9aA9a", # DISPERSER_REGISTRY
    "0x2E1BDB221E7D6bD9B7b2365208d41A5FD70b24Ed", # PAYMENT_VAULT
    "0x58D2B844a894f00b7E6F9F492b9F43aD54Cd4429", # CERT_VERIFIER
    "0x73818fed0743085c4557a736a7630447fb57c662", # CERT_VERIFIER_V1
    "0x73818fed0743085c4557a736a7630447fb57c662" # CERT_VERIFIER_V2
]

# The address of the proxy admin contract that manages the upgradeability of the contracts.
proxyAdmin = "0x562480eBb8B43474BCD864d827E7fA511D929F16"

# The privileged account that can manage the contract directory.
owner = "0xDF291ebfe90eF9187c3f45609603E366a21a16Ea"