// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// TO REGENERATE RUN inabox/deploy/codegen/gen.sh.
package deploy

import "reflect"

type DisperserVars struct {
	DISPERSER_SERVER_S3_BUCKET_NAME string

	DISPERSER_SERVER_DYNAMODB_TABLE_NAME string

	DISPERSER_SERVER_GRPC_PORT string

	DISPERSER_SERVER_RATE_BUCKET_TABLE_NAME string

	DISPERSER_SERVER_OBJECT_STORAGE_BACKEND string

	DISPERSER_SERVER_OCI_REGION string

	DISPERSER_SERVER_OCI_COMPARTMENT_ID string

	DISPERSER_SERVER_OCI_NAMESPACE string

	DISPERSER_SERVER_DISPERSER_VERSION string

	DISPERSER_SERVER_METRICS_HTTP_PORT string

	DISPERSER_SERVER_ENABLE_METRICS string

	DISPERSER_SERVER_ENABLE_RATELIMITER string

	DISPERSER_SERVER_ENABLE_PAYMENT_METERER string

	DISPERSER_SERVER_RATE_BUCKET_STORE_SIZE string

	DISPERSER_SERVER_GRPC_STREAM_TIMEOUT string

	DISPERSER_SERVER_MAX_CONNECTION_AGE_SECONDS string

	DISPERSER_SERVER_MAX_CONNECTION_AGE_GRACE_SECONDS string

	DISPERSER_SERVER_MAX_IDLE_CONNECTION_AGE_SECONDS string

	DISPERSER_SERVER_MAX_BLOB_SIZE string

	DISPERSER_SERVER_RESERVATIONS_TABLE_NAME string

	DISPERSER_SERVER_ON_DEMAND_TABLE_NAME string

	DISPERSER_SERVER_GLOBAL_RATE_TABLE_NAME string

	DISPERSER_SERVER_ONCHAIN_STATE_REFRESH_INTERVAL string

	DISPERSER_SERVER_MAX_NUM_SYMBOLS_PER_BLOB string

	DISPERSER_SERVER_PPROF_HTTP_PORT string

	DISPERSER_SERVER_ENABLE_PPROF string

	DISPERSER_SERVER_AUTH_PMT_REQUEST_MAX_PAST_AGE string

	DISPERSER_SERVER_AUTH_PMT_REQUEST_MAX_FUTURE_AGE string

	DISPERSER_SERVER_RESERVED_ONLY string

	DISPERSER_SERVER_CONTROLLER_ADDRESS string

	DISPERSER_SERVER_USE_CONTROLLER_MEDIATED_PAYMENTS string

	DISPERSER_SERVER_BLS_OPERATOR_STATE_RETRIVER string

	DISPERSER_SERVER_EIGENDA_SERVICE_MANAGER string

	DISPERSER_SERVER_EIGENDA_DIRECTORY string

	DISPERSER_SERVER_CHAIN_RPC string

	DISPERSER_SERVER_CHAIN_RPC_FALLBACK string

	DISPERSER_SERVER_PRIVATE_KEY string

	DISPERSER_SERVER_NUM_CONFIRMATIONS string

	DISPERSER_SERVER_NUM_RETRIES string

	DISPERSER_SERVER_LOG_LEVEL string

	DISPERSER_SERVER_LOG_PATH string

	DISPERSER_SERVER_LOG_FORMAT string

	DISPERSER_SERVER_BUCKET_SIZES string

	DISPERSER_SERVER_BUCKET_MULTIPLIERS string

	DISPERSER_SERVER_COUNT_FAILED string

	DISPERSER_SERVER_BUCKET_STORE_SIZE string

	DISPERSER_SERVER_AWS_REGION string

	DISPERSER_SERVER_AWS_ACCESS_KEY_ID string

	DISPERSER_SERVER_AWS_SECRET_ACCESS_KEY string

	DISPERSER_SERVER_AWS_ENDPOINT_URL string

	DISPERSER_SERVER_FRAGMENT_PREFIX_CHARS string

	DISPERSER_SERVER_FRAGMENT_PARALLELISM_FACTOR string

	DISPERSER_SERVER_FRAGMENT_PARALLELISM_CONSTANT string

	DISPERSER_SERVER_FRAGMENT_READ_TIMEOUT string

	DISPERSER_SERVER_FRAGMENT_WRITE_TIMEOUT string

	DISPERSER_SERVER_REGISTERED_QUORUM_ID string

	DISPERSER_SERVER_TOTAL_UNAUTH_BYTE_RATE string

	DISPERSER_SERVER_PER_USER_UNAUTH_BYTE_RATE string

	DISPERSER_SERVER_TOTAL_UNAUTH_BLOB_RATE string

	DISPERSER_SERVER_PER_USER_UNAUTH_BLOB_RATE string

	DISPERSER_SERVER_CLIENT_IP_HEADER string

	DISPERSER_SERVER_ALLOWLIST_FILE string

	DISPERSER_SERVER_ALLOWLIST_REFRESH_INTERVAL string

	DISPERSER_SERVER_RETRIEVAL_BLOB_RATE string

	DISPERSER_SERVER_RETRIEVAL_BYTE_RATE string

	DISPERSER_SERVER_G1_PATH string

	DISPERSER_SERVER_G2_PATH string

	DISPERSER_SERVER_G2_TRAILING_PATH string

	DISPERSER_SERVER_SRS_LOAD string
}

func (vars DisperserVars) getEnvMap() map[string]string {
	v := reflect.ValueOf(vars)
	envMap := make(map[string]string)
	for i := 0; i < v.NumField(); i++ {
		envMap[v.Type().Field(i).Name] = v.Field(i).String()
	}
	return envMap
}

type BatcherVars struct {
	BATCHER_S3_BUCKET_NAME string

	BATCHER_DYNAMODB_TABLE_NAME string

	BATCHER_PULL_INTERVAL string

	BATCHER_ENCODER_ADDRESS string

	BATCHER_ENABLE_METRICS string

	BATCHER_BATCH_SIZE_LIMIT string

	BATCHER_USE_GRAPH string

	BATCHER_SRS_ORDER string

	BATCHER_METRICS_HTTP_PORT string

	BATCHER_INDEXER_DATA_DIR string

	BATCHER_ENCODING_TIMEOUT string

	BATCHER_ATTESTATION_TIMEOUT string

	BATCHER_BATCH_ATTESTATION_TIMEOUT string

	BATCHER_CHAIN_READ_TIMEOUT string

	BATCHER_CHAIN_WRITE_TIMEOUT string

	BATCHER_CHAIN_STATE_TIMEOUT string

	BATCHER_TRANSACTION_BROADCAST_TIMEOUT string

	BATCHER_NUM_CONNECTIONS string

	BATCHER_FINALIZER_INTERVAL string

	BATCHER_FINALIZER_POOL_SIZE string

	BATCHER_ENCODING_REQUEST_QUEUE_SIZE string

	BATCHER_MAX_NUM_RETRIES_PER_BLOB string

	BATCHER_TARGET_NUM_CHUNKS string

	BATCHER_MAX_BLOBS_TO_FETCH_FROM_STORE string

	BATCHER_FINALIZATION_BLOCK_DELAY string

	BATCHER_MAX_NODE_CONNECTIONS string

	BATCHER_MAX_NUM_RETRIES_PER_DISPERSAL string

	BATCHER_ENABLE_GNARK_BUNDLE_ENCODING string

	BATCHER_BLS_OPERATOR_STATE_RETRIVER string

	BATCHER_EIGENDA_SERVICE_MANAGER string

	BATCHER_EIGENDA_DIRECTORY string

	BATCHER_OBJECT_STORAGE_BACKEND string

	BATCHER_OCI_REGION string

	BATCHER_OCI_COMPARTMENT_ID string

	BATCHER_OCI_NAMESPACE string

	BATCHER_CHAIN_RPC string

	BATCHER_CHAIN_RPC_FALLBACK string

	BATCHER_PRIVATE_KEY string

	BATCHER_NUM_CONFIRMATIONS string

	BATCHER_NUM_RETRIES string

	BATCHER_LOG_LEVEL string

	BATCHER_LOG_PATH string

	BATCHER_LOG_FORMAT string

	BATCHER_INDEXER_PULL_INTERVAL string

	BATCHER_AWS_REGION string

	BATCHER_AWS_ACCESS_KEY_ID string

	BATCHER_AWS_SECRET_ACCESS_KEY string

	BATCHER_AWS_ENDPOINT_URL string

	BATCHER_FRAGMENT_PREFIX_CHARS string

	BATCHER_FRAGMENT_PARALLELISM_FACTOR string

	BATCHER_FRAGMENT_PARALLELISM_CONSTANT string

	BATCHER_FRAGMENT_READ_TIMEOUT string

	BATCHER_FRAGMENT_WRITE_TIMEOUT string

	BATCHER_GRAPH_URL string

	BATCHER_GRAPH_BACKOFF string

	BATCHER_GRAPH_MAX_RETRIES string

	BATCHER_KMS_KEY_ID string

	BATCHER_KMS_KEY_REGION string

	BATCHER_KMS_KEY_DISABLE string
}

func (vars BatcherVars) getEnvMap() map[string]string {
	v := reflect.ValueOf(vars)
	envMap := make(map[string]string)
	for i := 0; i < v.NumField(); i++ {
		envMap[v.Type().Field(i).Name] = v.Field(i).String()
	}
	return envMap
}

type EncoderVars struct {
	ENCODER_AWS_REGION string

	ENCODER_AWS_ACCESS_KEY string

	ENCODER_AWS_SECRET_ACCESS_KEY string

	ENCODER_AWS_ENDPOINT_URL string

	ENCODER_AWS_FRAGMENT_PARALLELISM_FACTOR string

	ENCODER_AWS_FRAGMENT_PARALLELISM_CONSTANT string

	ENCODER_GRPC_PORT string

	ENCODER_METRICS_PORT string

	ENCODER_ENABLE_METRICS string

	ENCODER_SERVER_MAX_CONCURRENT_REQUESTS_DANGEROUS string

	ENCODER_SERVER_REQUEST_POOL_SIZE string

	ENCODER_SERVER_REQUEST_QUEUE_SIZE string

	ENCODER_SERVER_ENABLE_GNARK_CHUNK_ENCODING string

	ENCODER_VERSION string

	ENCODER_BLOB_STORE_BUCKET_NAME string

	ENCODER_BLOB_STORE_BACKEND string

	ENCODER_BLOB_STORE_OCI_REGION string

	ENCODER_BLOB_STORE_OCI_COMPARTMENT_ID string

	ENCODER_BLOB_STORE_OCI_NAMESPACE string

	ENCODER_CHUNK_STORE_BUCKET_NAME string

	ENCODER_SERVER_GPU_ENABLE string

	ENCODER_SERVER_BACKEND string

	ENCODER_SERVER_PREVENT_REENCODING string

	ENCODER_SERVER_PPROF_HTTP_PORT string

	ENCODER_SERVER_ENABLE_PPROF string

	ENCODER_KZG_G1_PATH string

	ENCODER_KZG_G2_PATH string

	ENCODER_KZG_G2_TRAILING_PATH string

	ENCODER_KZG_CACHE_DIR string

	ENCODER_KZG_SRS_ORDER string

	ENCODER_KZG_SRS_NUMBER_TO_LOAD string

	ENCODER_KZG_NUM_WORKER string

	ENCODER_KZG_VERBOSE string

	ENCODER_KZG_PRELOAD_ENCODER string

	ENCODER_LOG_PATH string

	ENCODER_LOG_FORMAT string

	ENCODER_LOG_LEVEL string
}

func (vars EncoderVars) getEnvMap() map[string]string {
	v := reflect.ValueOf(vars)
	envMap := make(map[string]string)
	for i := 0; i < v.NumField(); i++ {
		envMap[v.Type().Field(i).Name] = v.Field(i).String()
	}
	return envMap
}

type OperatorVars struct {
	NODE_HOSTNAME string

	NODE_DISPERSAL_PORT string

	NODE_RETRIEVAL_PORT string

	NODE_ENABLE_METRICS string

	NODE_METRICS_PORT string

	NODE_ONCHAIN_METRICS_INTERVAL string

	NODE_ENABLE_NODE_API string

	NODE_API_PORT string

	NODE_TIMEOUT string

	NODE_QUORUM_ID_LIST string

	NODE_DB_PATH string

	NODE_BLS_KEY_FILE string

	NODE_BLS_KEY_PASSWORD string

	NODE_PUBLIC_IP_PROVIDER string

	NODE_PUBLIC_IP_CHECK_INTERVAL string

	NODE_CHURNER_URL string

	NODE_REGISTER_AT_NODE_START string

	NODE_EXPIRATION_POLL_INTERVAL string

	NODE_REACHABILITY_POLL_INTERVAL string

	NODE_ENABLE_TEST_MODE string

	NODE_OVERRIDE_BLOCK_STALE_MEASURE string

	NODE_OVERRIDE_STORE_DURATION_BLOCKS string

	NODE_TEST_PRIVATE_BLS string

	NODE_NUM_BATCH_VALIDATORS string

	NODE_NUM_BATCH_DESERIALIZATION_WORKERS string

	NODE_INTERNAL_DISPERSAL_PORT string

	NODE_INTERNAL_RETRIEVAL_PORT string

	NODE_INTERNAL_V2_DISPERSAL_PORT string

	NODE_INTERNAL_V2_RETRIEVAL_PORT string

	NODE_CLIENT_IP_HEADER string

	NODE_CHURNER_USE_SECURE_GRPC string

	NODE_RELAY_USE_SECURE_GRPC string

	NODE_ECDSA_KEY_FILE string

	NODE_ECDSA_KEY_PASSWORD string

	NODE_DATAAPI_URL string

	NODE_DISABLE_NODE_INFO_RESOURCES string

	NODE_ENABLE_GNARK_BUNDLE_ENCODING string

	NODE_BLS_REMOTE_SIGNER_ENABLED string

	NODE_BLS_REMOTE_SIGNER_URL string

	NODE_BLS_PUBLIC_KEY_HEX string

	NODE_BLS_SIGNER_CERT_FILE string

	NODE_BLS_SIGNER_API_KEY string

	NODE_V2_DISPERSAL_PORT string

	NODE_V2_RETRIEVAL_PORT string

	NODE_ONCHAIN_STATE_REFRESH_INTERVAL string

	NODE_CHUNK_DOWNLOAD_TIMEOUT string

	NODE_GRPC_MSG_SIZE_LIMIT_V2 string

	NODE_PPROF_HTTP_PORT string

	NODE_ENABLE_PPROF string

	NODE_DISPERSAL_AUTHENTICATION_KEY_CACHE_SIZE string

	NODE_DISPERSER_KEY_TIMEOUT string

	NODE_DISPERSAL_AUTHENTICATION_TIMEOUT string

	NODE_RELAY_MAX_GRPC_MESSAGE_SIZE string

	NODE_RELAY_CONNECTION_POOL_SIZE string

	NODE_RUNTIME_MODE string

	NODE_STORE_CHUNKS_REQUEST_MAX_PAST_AGE string

	NODE_STORE_CHUNKS_REQUEST_MAX_FUTURE_AGE string

	NODE_LEVELDB_DISABLE_SEEKS_COMPACTION_V1 string

	NODE_LEVELDB_ENABLE_SYNC_WRITES_V1 string

	NODE_DOWNLOAD_POOL_SIZE string

	NODE_LITT_DB_WRITE_CACHE_SIZE_GB string

	NODE_LITT_DB_READ_CACHE_SIZE_GB string

	NODE_LITT_DB_WRITE_CACHE_SIZE_FRACTION string

	NODE_LITT_DB_READ_CACHE_SIZE_FRACTION string

	NODE_LITT_DB_STORAGE_PATHS string

	NODE_LITT_MINIMUM_FLUSH_INTERVAL string

	NODE_GET_CHUNKS_HOT_CACHE_READ_LIMIT_MB string

	NODE_GET_CHUNKS_HOT_BURST_LIMIT_MB string

	NODE_GET_CHUNKS_COLD_CACHE_READ_LIMIT_MB string

	NODE_GET_CHUNKS_COLD_BURST_LIMIT_MB string

	NODE_GC_SAFETY_BUFFER_SIZE_GB string

	NODE_EIGENDA_DIRECTORY string

	NODE_LITT_RESPECT_LOCKS string

	NODE_STORE_CHUNKS_BUFFER_TIMEOUT string

	NODE_STORE_CHUNKS_BUFFER_SIZE_GB string

	NODE_STORE_CHUNKS_BUFFER_SIZE_FRACTION string

	NODE_OPERATOR_STATE_CACHE_SIZE string

	NODE_LITT_SNAPSHOT_DIRECTORY string

	NODE_EJECTION_SENTINEL_PERIOD string

	NODE_EJECTION_DEFENSE_ENABLED string

	NODE_IGNORE_VERSION_FOR_EJECTION_DEFENSE string

	NODE_ENABLE_PAYMENT_VALIDATION string

	NODE_RESERVATION_MAX_LEDGERS string

	NODE_PAYMENT_VAULT_UPDATE_INTERVAL string

	NODE_G1_PATH string

	NODE_G2_PATH string

	NODE_G2_TRAILING_PATH string

	NODE_CACHE_PATH string

	NODE_SRS_ORDER string

	NODE_SRS_LOAD string

	NODE_NUM_WORKERS string

	NODE_VERBOSE string

	NODE_CACHE_ENCODED_BLOBS string

	NODE_PRELOAD_ENCODER string

	NODE_G2_POWER_OF_2_PATH string

	NODE_CHAIN_RPC string

	NODE_CHAIN_RPC_FALLBACK string

	NODE_PRIVATE_KEY string

	NODE_NUM_CONFIRMATIONS string

	NODE_NUM_RETRIES string

	NODE_LOG_LEVEL string

	NODE_LOG_PATH string

	NODE_LOG_FORMAT string
}

func (vars OperatorVars) getEnvMap() map[string]string {
	v := reflect.ValueOf(vars)
	envMap := make(map[string]string)
	for i := 0; i < v.NumField(); i++ {
		envMap[v.Type().Field(i).Name] = v.Field(i).String()
	}
	return envMap
}

type RetrieverVars struct {
	RETRIEVER_HOSTNAME string

	RETRIEVER_GRPC_PORT string

	RETRIEVER_TIMEOUT string

	RETRIEVER_EIGENDA_DIRECTORY string

	RETRIEVER_BLS_OPERATOR_STATE_RETRIVER string

	RETRIEVER_EIGENDA_SERVICE_MANAGER string

	RETRIEVER_NUM_CONNECTIONS string

	RETRIEVER_METRICS_HTTP_PORT string

	RETRIEVER_EIGENDA_VERSION string

	RETRIEVER_G1_PATH string

	RETRIEVER_G2_PATH string

	RETRIEVER_G2_TRAILING_PATH string

	RETRIEVER_CACHE_PATH string

	RETRIEVER_SRS_ORDER string

	RETRIEVER_SRS_LOAD string

	RETRIEVER_NUM_WORKERS string

	RETRIEVER_VERBOSE string

	RETRIEVER_CACHE_ENCODED_BLOBS string

	RETRIEVER_PRELOAD_ENCODER string

	RETRIEVER_G2_POWER_OF_2_PATH string

	RETRIEVER_CHAIN_RPC string

	RETRIEVER_CHAIN_RPC_FALLBACK string

	RETRIEVER_PRIVATE_KEY string

	RETRIEVER_NUM_CONFIRMATIONS string

	RETRIEVER_NUM_RETRIES string

	RETRIEVER_LOG_LEVEL string

	RETRIEVER_LOG_PATH string

	RETRIEVER_LOG_FORMAT string
}

func (vars RetrieverVars) getEnvMap() map[string]string {
	v := reflect.ValueOf(vars)
	envMap := make(map[string]string)
	for i := 0; i < v.NumField(); i++ {
		envMap[v.Type().Field(i).Name] = v.Field(i).String()
	}
	return envMap
}

type ChurnerVars struct {
	CHURNER_HOSTNAME string

	CHURNER_GRPC_PORT string

	CHURNER_ENABLE_METRICS string

	CHURNER_PER_PUBLIC_KEY_RATE_LIMIT string

	CHURNER_METRICS_HTTP_PORT string

	CHURNER_CHURN_APPROVAL_INTERVAL string

	CHURNER_EIGENDA_DIRECTORY string

	CHURNER_BLS_OPERATOR_STATE_RETRIVER string

	CHURNER_EIGENDA_SERVICE_MANAGER string

	CHURNER_CHAIN_RPC string

	CHURNER_CHAIN_RPC_FALLBACK string

	CHURNER_PRIVATE_KEY string

	CHURNER_NUM_CONFIRMATIONS string

	CHURNER_NUM_RETRIES string

	CHURNER_LOG_LEVEL string

	CHURNER_LOG_PATH string

	CHURNER_LOG_FORMAT string

	CHURNER_INDEXER_PULL_INTERVAL string

	CHURNER_GRAPH_URL string

	CHURNER_GRAPH_BACKOFF string

	CHURNER_GRAPH_MAX_RETRIES string
}

func (vars ChurnerVars) getEnvMap() map[string]string {
	v := reflect.ValueOf(vars)
	envMap := make(map[string]string)
	for i := 0; i < v.NumField(); i++ {
		envMap[v.Type().Field(i).Name] = v.Field(i).String()
	}
	return envMap
}

type ControllerVars struct {
	CONTROLLER_DYNAMODB_TABLE_NAME string

	CONTROLLER_USE_GRAPH string

	CONTROLLER_ENCODING_PULL_INTERVAL string

	CONTROLLER_AVAILABLE_RELAYS string

	CONTROLLER_ENCODER_ADDRESS string

	CONTROLLER_DISPATCHER_PULL_INTERVAL string

	CONTROLLER_ATTESTATION_TIMEOUT string

	CONTROLLER_BATCH_ATTESTATION_TIMEOUT string

	CONTROLLER_DISPERSER_ID string

	CONTROLLER_INDEXER_DATA_DIR string

	CONTROLLER_ENCODING_REQUEST_TIMEOUT string

	CONTROLLER_ENCODING_STORE_TIMEOUT string

	CONTROLLER_NUM_ENCODING_RETRIES string

	CONTROLLER_NUM_RELAY_ASSIGNMENT string

	CONTROLLER_NUM_CONCURRENT_ENCODING_REQUESTS string

	CONTROLLER_MAX_NUM_BLOBS_PER_ITERATION string

	CONTROLLER_ONCHAIN_STATE_REFRESH_INTERVAL string

	CONTROLLER_SIGNATURE_TICK_INTERVAL string

	CONTROLLER_FINALIZATION_BLOCK_DELAY string

	CONTROLLER_NUM_REQUEST_RETRIES string

	CONTROLLER_NUM_CONCURRENT_DISPERSAL_REQUESTS string

	CONTROLLER_NODE_CLIENT_CACHE_NUM_ENTRIES string

	CONTROLLER_MAX_BATCH_SIZE string

	CONTROLLER_METRICS_PORT string

	CONTROLLER_DISPERSER_STORE_CHUNKS_SIGNING_DISABLED string

	CONTROLLER_DISPERSER_KMS_KEY_ID string

	CONTROLLER_DISPERSER_PRIVATE_KEY string

	CONTROLLER_CONTROLLER_READINESS_PROBE_PATH string

	CONTROLLER_CONTROLLER_HEALTH_PROBE_PATH string

	CONTROLLER_HEARTBEAT_MAX_STALL_DURATION string

	CONTROLLER_SIGNIFICANT_SIGNING_THRESHOLD_PERCENTAGE string

	CONTROLLER_SIGNIFICANT_SIGNING_METRICS_THRESHOLDS string

	CONTROLLER_EIGENDA_CONTRACT_DIRECTORY_ADDRESS string

	CONTROLLER_BATCH_METADATA_UPDATE_PERIOD string

	CONTROLLER_GRPC_SERVER_ENABLE string

	CONTROLLER_GRPC_PAYMENT_AUTHENTICATION string

	CONTROLLER_GRPC_PORT string

	CONTROLLER_GRPC_MAX_MESSAGE_SIZE string

	CONTROLLER_GRPC_MAX_IDLE_CONNECTION_AGE string

	CONTROLLER_GRPC_AUTHORIZATION_REQUEST_MAX_PAST_AGE string

	CONTROLLER_GRPC_AUTHORIZATION_REQUEST_MAX_FUTURE_AGE string

	CONTROLLER_ON_DEMAND_PAYMENTS_TABLE_NAME string

	CONTROLLER_ONDEMAND_PAYMENTS_LEDGER_CACHE_SIZE string

	CONTROLLER_RESERVATION_PAYMENTS_LEDGER_CACHE_SIZE string

	CONTROLLER_PAYMENT_VAULT_UPDATE_INTERVAL string

	CONTROLLER_CHAIN_RPC string

	CONTROLLER_CHAIN_RPC_FALLBACK string

	CONTROLLER_PRIVATE_KEY string

	CONTROLLER_NUM_CONFIRMATIONS string

	CONTROLLER_NUM_RETRIES string

	CONTROLLER_LOG_LEVEL string

	CONTROLLER_LOG_PATH string

	CONTROLLER_LOG_FORMAT string

	CONTROLLER_INDEXER_PULL_INTERVAL string

	CONTROLLER_AWS_REGION string

	CONTROLLER_AWS_ACCESS_KEY_ID string

	CONTROLLER_AWS_SECRET_ACCESS_KEY string

	CONTROLLER_AWS_ENDPOINT_URL string

	CONTROLLER_FRAGMENT_PREFIX_CHARS string

	CONTROLLER_FRAGMENT_PARALLELISM_FACTOR string

	CONTROLLER_FRAGMENT_PARALLELISM_CONSTANT string

	CONTROLLER_FRAGMENT_READ_TIMEOUT string

	CONTROLLER_FRAGMENT_WRITE_TIMEOUT string

	CONTROLLER_GRAPH_URL string

	CONTROLLER_GRAPH_BACKOFF string

	CONTROLLER_GRAPH_MAX_RETRIES string
}

func (vars ControllerVars) getEnvMap() map[string]string {
	v := reflect.ValueOf(vars)
	envMap := make(map[string]string)
	for i := 0; i < v.NumField(); i++ {
		envMap[v.Type().Field(i).Name] = v.Field(i).String()
	}
	return envMap
}

type RelayVars struct {
	RELAY_GRPC_PORT string

	RELAY_BUCKET_NAME string

	RELAY_METADATA_TABLE_NAME string

	RELAY_RELAY_KEYS string

	RELAY_ENABLE_METRICS string

	RELAY_OBJECT_STORAGE_BACKEND string

	RELAY_OCI_REGION string

	RELAY_OCI_COMPARTMENT_ID string

	RELAY_OCI_NAMESPACE string

	RELAY_MAX_GRPC_MESSAGE_SIZE string

	RELAY_METADATA_CACHE_SIZE string

	RELAY_METADATA_MAX_CONCURRENCY string

	RELAY_BLOB_CACHE_SIZE string

	RELAY_BLOB_MAX_CONCURRENCY string

	RELAY_CHUNK_CACHE_BYTES string

	RELAY_CHUNK_MAX_CONCURRENCY string

	RELAY_MAX_KEYS_PER_GET_CHUNKS_REQUEST string

	RELAY_MAX_GET_BLOB_OPS_PER_SECOND string

	RELAY_GET_BLOB_OPS_BURSTINESS string

	RELAY_MAX_GET_BLOB_BYTES_PER_SECOND string

	RELAY_GET_BLOB_BYTES_BURSTINESS string

	RELAY_MAX_CONCURRENT_GET_BLOB_OPS string

	RELAY_MAX_GET_CHUNK_OPS_PER_SECOND string

	RELAY_GET_CHUNK_OPS_BURSTINESS string

	RELAY_MAX_GET_CHUNK_BYTES_PER_SECOND string

	RELAY_GET_CHUNK_BYTES_BURSTINESS string

	RELAY_MAX_CONCURRENT_GET_CHUNK_OPS string

	RELAY_MAX_GET_CHUNK_OPS_PER_SECOND_CLIENT string

	RELAY_GET_CHUNK_OPS_BURSTINESS_CLIENT string

	RELAY_MAX_GET_CHUNK_BYTES_PER_SECOND_CLIENT string

	RELAY_GET_CHUNK_BYTES_BURSTINESS_CLIENT string

	RELAY_MAX_CONCURRENT_GET_CHUNK_OPS_CLIENT string

	RELAY_AUTHENTICATION_KEY_CACHE_SIZE string

	RELAY_AUTHENTICATION_TIMEOUT string

	RELAY_AUTHENTICATION_DISABLED string

	RELAY_GET_CHUNKS_TIMEOUT string

	RELAY_GET_BLOB_TIMEOUT string

	RELAY_INTERNAL_GET_METADATA_TIMEOUT string

	RELAY_INTERNAL_GET_BLOB_TIMEOUT string

	RELAY_INTERNAL_GET_PROOFS_TIMEOUT string

	RELAY_INTERNAL_GET_COEFFICIENTS_TIMEOUT string

	RELAY_ONCHAIN_STATE_REFRESH_INTERVAL string

	RELAY_METRICS_PORT string

	RELAY_ENABLE_PPROF string

	RELAY_PPROF_PORT string

	RELAY_GET_CHUNKS_REQUEST_MAX_PAST_AGE string

	RELAY_GET_CHUNKS_REQUEST_MAX_FUTURE_AGE string

	RELAY_EIGENDA_DIRECTORY string

	RELAY_BLS_OPERATOR_STATE_RETRIEVER_ADDR string

	RELAY_EIGEN_DA_SERVICE_MANAGER_ADDR string

	RELAY_MAX_CONNECTION_AGE_SECONDS string

	RELAY_MAX_CONNECTION_AGE_GRACE_SECONDS string

	RELAY_MAX_IDLE_CONNECTION_AGE_SECONDS string

	RELAY_LOG_LEVEL string

	RELAY_LOG_PATH string

	RELAY_LOG_FORMAT string

	RELAY_AWS_REGION string

	RELAY_AWS_ACCESS_KEY_ID string

	RELAY_AWS_SECRET_ACCESS_KEY string

	RELAY_AWS_ENDPOINT_URL string

	RELAY_FRAGMENT_PREFIX_CHARS string

	RELAY_FRAGMENT_PARALLELISM_FACTOR string

	RELAY_FRAGMENT_PARALLELISM_CONSTANT string

	RELAY_FRAGMENT_READ_TIMEOUT string

	RELAY_FRAGMENT_WRITE_TIMEOUT string

	RELAY_CHAIN_RPC string

	RELAY_CHAIN_RPC_FALLBACK string

	RELAY_PRIVATE_KEY string

	RELAY_NUM_CONFIRMATIONS string

	RELAY_NUM_RETRIES string

	RELAY_GRAPH_URL string

	RELAY_GRAPH_BACKOFF string

	RELAY_GRAPH_MAX_RETRIES string
}

func (vars RelayVars) getEnvMap() map[string]string {
	v := reflect.ValueOf(vars)
	envMap := make(map[string]string)
	for i := 0; i < v.NumField(); i++ {
		envMap[v.Type().Field(i).Name] = v.Field(i).String()
	}
	return envMap
}

type ProxyVars struct {
	EIGENDA_PROXY_APIS_TO_ENABLE string

	EIGENDA_PROXY_ADDR string

	EIGENDA_PROXY_PORT string

	EIGENDA_PROXY_ARB_DA_ADDR string

	EIGENDA_PROXY_ARB_DA_PORT string

	EIGENDA_PROXY_METRICS_ADDR string

	EIGENDA_PROXY_METRICS_PORT string

	EIGENDA_PROXY_LOG_LEVEL string

	EIGENDA_PROXY_LOG_PATH string

	EIGENDA_PROXY_LOG_FORMAT string

	EIGENDA_PROXY_LOG_PID string

	EIGENDA_PROXY_LOG_COLOR string

	EIGENDA_PROXY_EIGENDA_DISPERSER_RPC string

	EIGENDA_PROXY_EIGENDA_RESPONSE_TIMEOUT string

	EIGENDA_PROXY_EIGENDA_CONFIRMATION_TIMEOUT string

	EIGENDA_PROXY_EIGENDA_STATUS_QUERY_TIMEOUT string

	EIGENDA_PROXY_EIGENDA_STATUS_QUERY_INTERVAL string

	EIGENDA_PROXY_EIGENDA_GRPC_DISABLE_TLS string

	EIGENDA_PROXY_EIGENDA_CUSTOM_QUORUM_IDS string

	EIGENDA_PROXY_EIGENDA_SIGNER_PRIVATE_KEY_HEX string

	EIGENDA_PROXY_EIGENDA_PUT_BLOB_ENCODING_VERSION string

	EIGENDA_PROXY_EIGENDA_DISABLE_POINT_VERIFICATION_MODE string

	EIGENDA_PROXY_EIGENDA_CONFIRMATION_DEPTH string

	EIGENDA_PROXY_EIGENDA_ETH_RPC string

	EIGENDA_PROXY_EIGENDA_SERVICE_MANAGER_ADDR string

	EIGENDA_PROXY_EIGENDA_PUT_RETRIES string

	EIGENDA_PROXY_EIGENDA_MAX_BLOB_LENGTH string

	EIGENDA_PROXY_EIGENDA_V2_DISPERSER_RPC string

	EIGENDA_PROXY_EIGENDA_V2_GRPC_DISABLE_TLS string

	EIGENDA_PROXY_EIGENDA_V2_SIGNER_PRIVATE_KEY_HEX string

	EIGENDA_PROXY_EIGENDA_V2_DISABLE_POINT_EVALUATION string

	EIGENDA_PROXY_EIGENDA_V2_ETH_RPC string

	EIGENDA_PROXY_EIGENDA_V2_PUT_RETRIES string

	EIGENDA_PROXY_EIGENDA_V2_DISPERSE_BLOB_TIMEOUT string

	EIGENDA_PROXY_EIGENDA_V2_CERTIFY_BLOB_TIMEOUT string

	EIGENDA_PROXY_EIGENDA_V2_CERT_VERIFIER_ROUTER_OR_IMMUTABLE_VERIFIER_ADDR string

	EIGENDA_PROXY_EIGENDA_V2_EIGENDA_DIRECTORY string

	EIGENDA_PROXY_EIGENDA_V2_CONTRACT_CALL_TIMEOUT string

	EIGENDA_PROXY_EIGENDA_V2_RELAY_TIMEOUT string

	EIGENDA_PROXY_EIGENDA_V2_VALIDATOR_TIMEOUT string

	EIGENDA_PROXY_EIGENDA_V2_BLOB_STATUS_POLL_INTERVAL string

	EIGENDA_PROXY_EIGENDA_V2_BLOB_PARAMS_VERSION string

	EIGENDA_PROXY_EIGENDA_V2_MAX_BLOB_LENGTH string

	EIGENDA_PROXY_EIGENDA_V2_NETWORK string

	EIGENDA_PROXY_EIGENDA_V2_RBN_RECENCY_WINDOW_SIZE string

	EIGENDA_PROXY_EIGENDA_V2_RELAY_CONNECTION_POOL_SIZE string

	EIGENDA_PROXY_EIGENDA_V2_CLIENT_LEDGER_MODE string

	EIGENDA_PROXY_EIGENDA_V2_PAYMENT_VAULT_MONITOR_INTERVAL string

	EIGENDA_PROXY_STORAGE_BACKENDS_TO_ENABLE string

	EIGENDA_PROXY_STORAGE_DISPERSAL_BACKEND string

	EIGENDA_PROXY_STORAGE_FALLBACK_TARGETS string

	EIGENDA_PROXY_STORAGE_CACHE_TARGETS string

	EIGENDA_PROXY_STORAGE_CONCURRENT_WRITE_THREADS string

	EIGENDA_PROXY_STORAGE_WRITE_ON_CACHE_MISS string

	EIGENDA_PROXY_STORAGE_ERROR_ON_SECONDARY_INSERT_FAILURE string

	EIGENDA_PROXY_S3_ENDPOINT string

	EIGENDA_PROXY_S3_ENABLE_TLS string

	EIGENDA_PROXY_S3_CREDENTIAL_TYPE string

	EIGENDA_PROXY_S3_ACCESS_KEY_ID string

	EIGENDA_PROXY_S3_ACCESS_KEY_SECRET string

	EIGENDA_PROXY_S3_BUCKET string

	EIGENDA_PROXY_S3_PATH string

	EIGENDA_PROXY_MEMSTORE_ENABLED string

	EIGENDA_PROXY_MEMSTORE_EXPIRATION string

	EIGENDA_PROXY_MEMSTORE_PUT_LATENCY string

	EIGENDA_PROXY_MEMSTORE_GET_LATENCY string

	EIGENDA_PROXY_MEMSTORE_PUT_RETURNS_FAILOVER_ERROR string

	EIGENDA_PROXY_EIGENDA_CERT_VERIFICATION_DISABLED string

	EIGENDA_PROXY_EIGENDA_CERT_VERIFIER_V1 string

	EIGENDA_PROXY_EIGENDA_TARGET_KZG_G1_PATH string

	EIGENDA_PROXY_EIGENDA_TARGET_KZG_G2_POWER_OF_2_PATH string

	EIGENDA_PROXY_EIGENDA_TARGET_KZG_G2_PATH string

	EIGENDA_PROXY_EIGENDA_TARGET_KZG_G2_TRAILING_PATH string

	EIGENDA_PROXY_EIGENDA_TARGET_CACHE_PATH string

	EIGENDA_PROXY_METRICS_ENABLED string

	EIGENDA_PROXY_DISPERSER_RPC string

	EIGENDA_PROXY_STATUS_QUERY_TIMEOUT string

	EIGENDA_PROXY_STATUS_QUERY_INTERVAL string

	EIGENDA_PROXY_GRPC_DISABLE_TLS string

	EIGENDA_PROXY_RESPONSE_TIMEOUT string

	EIGENDA_PROXY_CUSTOM_QUORUM_IDS string

	EIGENDA_PROXY_SIGNER_PRIVATE_KEY_HEX string

	EIGENDA_PROXY_PUT_BLOB_ENCODING_VERSION string

	EIGENDA_PROXY_DISABLE_POINT_VERIFICATION_MODE string

	EIGENDA_PROXY_EIGENDA_V2_SERVICE_MANAGER_ADDR string

	EIGENDA_PROXY_EIGENDA_V2_BLS_OPERATOR_STATE_RETRIEVER_ADDR string

	EIGENDA_PROXY_ETH_RPC string

	EIGENDA_PROXY_SERVICE_MANAGER_ADDR string

	EIGENDA_PROXY_ETH_CONFIRMATION_DEPTH string

	EIGENDA_PROXY_TARGET_KZG_G1_PATH string

	EIGENDA_PROXY_TARGET_G2_TAU_PATH string

	EIGENDA_PROXY_TARGET_CACHE_PATH string

	EIGENDA_PROXY_MAX_BLOB_LENGTH string

	EIGENDA_PROXY_FALLBACK_TARGETS string

	EIGENDA_PROXY_CACHE_TARGETS string

	EIGENDA_PROXY_CONCURRENT_WRITE_THREADS string

	EIGENDA_PROXY_REDIS_ENDPOINT string

	EIGENDA_PROXY_REDIS_PASSWORD string

	EIGENDA_PROXY_REDIS_DB string

	EIGENDA_PROXY_REDIS_EVICTION string
}

func (vars ProxyVars) getEnvMap() map[string]string {
	v := reflect.ValueOf(vars)
	envMap := make(map[string]string)
	for i := 0; i < v.NumField(); i++ {
		envMap[v.Type().Field(i).Name] = v.Field(i).String()
	}
	return envMap
}
