// Code generated by mockery v2.50.0. DO NOT EDIT.

package mock

import (
	"context"

	"github.com/Layr-Labs/eigenda/api/clients/v2/verification"
	"github.com/stretchr/testify/mock"
)

// MockBlobVerifier is an autogenerated mock type for the MockBlobVerifier type
type MockBlobVerifier struct {
	mock.Mock
}

// VerifyBlobV2 provides a mock function with given fields: ctx, eigenDACert
func (_m *MockBlobVerifier) VerifyBlobV2(ctx context.Context, eigenDACert *verification.EigenDACert) error {
	ret := _m.Called(ctx, eigenDACert)

	if len(ret) == 0 {
		panic("no return value specified for VerifyBlobV2")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *verification.EigenDACert) error); ok {
		r0 = rf(ctx, eigenDACert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockBlobVerifier creates a new instance of MockBlobVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobVerifier {
	mock := &MockBlobVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
