// Code generated by mockery v2.50.0. DO NOT EDIT.

package mock

import (
	"context"

	contractEigenDABlobVerifier "github.com/Layr-Labs/eigenda/contracts/bindings/EigenDABlobVerifier"
	"github.com/stretchr/testify/mock"

	v2 "github.com/Layr-Labs/eigenda/api/grpc/disperser/v2"

	"github.com/Layr-Labs/eigenda/api/clients/v2/verification"
)

// MockBlobVerifier is an autogenerated mock type for the IBlobVerifier type
type MockBlobVerifier struct {
	mock.Mock
}

// GetNonSignerStakesAndSignature provides a mock function with given fields: ctx, signedBatch
func (_m *MockBlobVerifier) GetNonSignerStakesAndSignature(ctx context.Context, signedBatch *v2.SignedBatch) (*contractEigenDABlobVerifier.NonSignerStakesAndSignature, error) {
	ret := _m.Called(ctx, signedBatch)

	if len(ret) == 0 {
		panic("no return value specified for GetNonSignerStakesAndSignature")
	}

	var r0 *contractEigenDABlobVerifier.NonSignerStakesAndSignature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.SignedBatch) (*contractEigenDABlobVerifier.NonSignerStakesAndSignature, error)); ok {
		return rf(ctx, signedBatch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.SignedBatch) *contractEigenDABlobVerifier.NonSignerStakesAndSignature); ok {
		r0 = rf(ctx, signedBatch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contractEigenDABlobVerifier.NonSignerStakesAndSignature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.SignedBatch) error); ok {
		r1 = rf(ctx, signedBatch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyBlobV2 provides a mock function with given fields: ctx, eigenDACert
func (_m *MockBlobVerifier) VerifyBlobV2(ctx context.Context, eigenDACert *verification.EigenDACert) error {
	ret := _m.Called(ctx, eigenDACert)

	if len(ret) == 0 {
		panic("no return value specified for VerifyBlobV2")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *verification.EigenDACert) error); ok {
		r0 = rf(ctx, eigenDACert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockBlobVerifier creates a new instance of MockBlobVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobVerifier {
	mock := &MockBlobVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
