[profile.default]
src = 'BLSApkRegistry'
out = 'out'
libs = ['lib']

# Compilation settings from Etherscan
solc_version = '0.8.12'
optimizer = true
optimizer_runs = 200
evm_version = 'london'

# Remappings for the project
remappings = [
  "@openzeppelin-upgrades/=BLSApkRegistry/lib/openzeppelin-contracts-upgradeable/",
  "@openzeppelin/=BLSApkRegistry/lib/openzeppelin-contracts/",
  "eigenlayer-middleware/=BLSApkRegistry/lib/eigenlayer-middleware/src/",
  "eigenlayer-core/=BLSApkRegistry/lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/",
  "eigenlayer-contracts/=BLSApkRegistry/lib/eigenlayer-middleware/lib/eigenlayer-contracts/"
]
