[profile.default]
src = 'EjectionManager/src'
out = 'out'
libs = ['lib']

# Compilation settings from Etherscan
solc_version = '0.8.12'
optimizer = true
optimizer_runs = 200
evm_version = 'london'

# Remappings for this contract (with src/ subdirectory)
remappings = [
  "@openzeppelin-upgrades/=EjectionManager/lib/openzeppelin-contracts-upgradeable/",
  "@openzeppelin/=EjectionManager/lib/openzeppelin-contracts/",
  "eigenlayer-contracts/=EjectionManager/lib/eigenlayer-contracts/"
]
