// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: retriever/retriever.proto

package retriever

import (
	context "context"
	common "github.com/Layr-Labs/eigenda/api/grpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Retriever_RetrieveBlob_FullMethodName = "/retriever.Retriever/RetrieveBlob"
	Retriever_GetBlob_FullMethodName      = "/retriever.Retriever/GetBlob"
)

// RetrieverClient is the client API for Retriever service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Retriever is a service for retrieving chunks corresponding to a blob from
// the EigenDA operator nodes and reconstructing the original blob from the chunks.
// This is a client-side library that the users are supposed to operationalize.
//
// Note: Users generally have two ways to retrieve a blob from EigenDA:
//  1. Retrieve from the Disperser that the user initially used for dispersal: the API
//     is Disperser.RetrieveBlob() as defined in api/proto/disperser/disperser.proto
//  2. Retrieve directly from the EigenDA Nodes, which is supported by this Retriever.
//
// The Disperser.RetrieveBlob() (the 1st approach) is generally faster and cheaper as the
// Disperser manages the blobs that it has processed, whereas the Retriever.RetrieveBlob()
// (the 2nd approach here) removes the need to trust the Disperser, with the downside of
// worse cost and performance.
type RetrieverClient interface {
	// This fans out request to EigenDA Nodes to retrieve the chunks and returns the
	// reconstructed original blob in response.
	RetrieveBlob(ctx context.Context, in *BlobRequest, opts ...grpc.CallOption) (*BlobReply, error)
	// Obtain the chunks necessary to reconstruct a blob and return it.
	// Eventually this will replace RetrieveBlob.
	GetBlob(ctx context.Context, in *common.BlobKey, opts ...grpc.CallOption) (*common.BlobData, error)
}

type retrieverClient struct {
	cc grpc.ClientConnInterface
}

func NewRetrieverClient(cc grpc.ClientConnInterface) RetrieverClient {
	return &retrieverClient{cc}
}

func (c *retrieverClient) RetrieveBlob(ctx context.Context, in *BlobRequest, opts ...grpc.CallOption) (*BlobReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlobReply)
	err := c.cc.Invoke(ctx, Retriever_RetrieveBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrieverClient) GetBlob(ctx context.Context, in *common.BlobKey, opts ...grpc.CallOption) (*common.BlobData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BlobData)
	err := c.cc.Invoke(ctx, Retriever_GetBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RetrieverServer is the server API for Retriever service.
// All implementations must embed UnimplementedRetrieverServer
// for forward compatibility.
//
// The Retriever is a service for retrieving chunks corresponding to a blob from
// the EigenDA operator nodes and reconstructing the original blob from the chunks.
// This is a client-side library that the users are supposed to operationalize.
//
// Note: Users generally have two ways to retrieve a blob from EigenDA:
//  1. Retrieve from the Disperser that the user initially used for dispersal: the API
//     is Disperser.RetrieveBlob() as defined in api/proto/disperser/disperser.proto
//  2. Retrieve directly from the EigenDA Nodes, which is supported by this Retriever.
//
// The Disperser.RetrieveBlob() (the 1st approach) is generally faster and cheaper as the
// Disperser manages the blobs that it has processed, whereas the Retriever.RetrieveBlob()
// (the 2nd approach here) removes the need to trust the Disperser, with the downside of
// worse cost and performance.
type RetrieverServer interface {
	// This fans out request to EigenDA Nodes to retrieve the chunks and returns the
	// reconstructed original blob in response.
	RetrieveBlob(context.Context, *BlobRequest) (*BlobReply, error)
	// Obtain the chunks necessary to reconstruct a blob and return it.
	// Eventually this will replace RetrieveBlob.
	GetBlob(context.Context, *common.BlobKey) (*common.BlobData, error)
	mustEmbedUnimplementedRetrieverServer()
}

// UnimplementedRetrieverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRetrieverServer struct{}

func (UnimplementedRetrieverServer) RetrieveBlob(context.Context, *BlobRequest) (*BlobReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveBlob not implemented")
}
func (UnimplementedRetrieverServer) GetBlob(context.Context, *common.BlobKey) (*common.BlobData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlob not implemented")
}
func (UnimplementedRetrieverServer) mustEmbedUnimplementedRetrieverServer() {}
func (UnimplementedRetrieverServer) testEmbeddedByValue()                   {}

// UnsafeRetrieverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RetrieverServer will
// result in compilation errors.
type UnsafeRetrieverServer interface {
	mustEmbedUnimplementedRetrieverServer()
}

func RegisterRetrieverServer(s grpc.ServiceRegistrar, srv RetrieverServer) {
	// If the following call pancis, it indicates UnimplementedRetrieverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Retriever_ServiceDesc, srv)
}

func _Retriever_RetrieveBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieverServer).RetrieveBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Retriever_RetrieveBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieverServer).RetrieveBlob(ctx, req.(*BlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Retriever_GetBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.BlobKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieverServer).GetBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Retriever_GetBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieverServer).GetBlob(ctx, req.(*common.BlobKey))
	}
	return interceptor(ctx, in, info, handler)
}

// Retriever_ServiceDesc is the grpc.ServiceDesc for Retriever service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Retriever_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "retriever.Retriever",
	HandlerType: (*RetrieverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveBlob",
			Handler:    _Retriever_RetrieveBlob_Handler,
		},
		{
			MethodName: "GetBlob",
			Handler:    _Retriever_GetBlob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "retriever/retriever.proto",
}
