environment:
  name: "staging"
  type: "local"

deployers:
- name: "default"
  rpc: http://localhost:8545
  verifyContracts: false
  verifierUrl: http://localhost:4000/api
  slow: false

eigenda:
  deployer: "default"

blobVersions:
  - codingRate: 8
    numChunks: 8192
    maxNumOperators: 3537

privateKeys:

services:
  counts:
    operators: 4
    relays: 4
  stakes:
    total: 100e18
    distribution: [1.3, 2, 3, 5]
  basePort: 32000
  variables:
    globals:
      HOSTNAME: localhost
      TIMEOUT: 20s
      CHAIN_RPC: http://localhost:8545
      CHAIN_ID: 40525
      G1_PATH: resources/kzg/g1.point.300000
      G2_PATH: resources/kzg/g2.point.300000
      G2_POWER_OF_2_PATH: resources/kzg/g2.point.300000.powerOf2
      CACHE_PATH: resources/kzg/SRSTables
      SRS_ORDER: 10000
      SRS_LOAD: 10000
      CHALLENGE_ORDER: 10000
      LOG_LEVEL: "debug"
      LOG_FORMAT: "text"
      VERBOSE: true
