{
 "title": "EigenDA Load Generator (Single Host)",
 "description": "Metrics for the EigenDA load generator (single host)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Dispersal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dispersal Stage Latency",
   "type": "piechart",
   "description": "A breakdown of the latency spent in each stage of a dispersal lifecycle.",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(PayloadDisperser_SendPayload_stage_latency_ms_sum[5m])) by (stage)\n/\nsum(rate(PayloadDisperser_SendPayload_stage_latency_ms_count[5m])) by (stage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dispersal Successes / Second",
   "type": "timeseries",
   "description": "A count of dispersal successes per second.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "increase(eigenda_test_client_dispersal_successes[$__rate_interval]) / $__rate_interval",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(eigenda_test_client_dispersal_successes[$__rate_interval]) / $__rate_interval)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Dispersal Failures / Second",
   "type": "timeseries",
   "description": "A count of dispersal failures per second.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "increase(eigenda_test_client_dispersal_failures[$__rate_interval]) / $__rate_interval",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(eigenda_test_client_dispersal_failures[$__rate_interval]) / $__rate_interval)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Dispersals In Flight",
   "type": "timeseries",
   "description": "Number of dispersal operations in flight",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eigenda_test_client_operations_in_flight{operation=\"dispersal\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(eigenda_test_client_operations_in_flight{operation=\"dispersal\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Average Dispersal Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(eigenda_test_client_dispersal_time_ms_sum[$__rate_interval]))\n/\nsum(rate(eigenda_test_client_dispersal_time_ms_count[$__rate_interval]))",
     "legendFormat": "average"
    },
    {
     "expr": "sum by (instance) (rate(eigenda_test_client_dispersal_time_ms_sum[$__rate_interval]))\n/\nsum by (instance) (rate(eigenda_test_client_dispersal_time_ms_count[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Dispersal Latency By Phase",
   "type": "timeseries",
   "description": "The average latency that the blob spends in various statuses.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (stage) (rate(PayloadDisperser_SendPayload_stage_latency_ms_sum[5m]))\n/\nsum by (stage) (rate(PayloadDisperser_SendPayload_stage_latency_ms_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dispersal Stage Count",
   "type": "timeseries",
   "description": "For all blobs in flight, the number of blobs in each stage of dispersal.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (stage)(PayloadDisperser_SendPayload_stage_count)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "P99 Dispersal Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "eigenda_test_client_dispersal_time_ms{quantile=\"0.99\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dispersal Latency Thresholds",
   "type": "timeseries",
   "description": "Time taken to disperse a blob, broken down by various thresholds.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(eigenda_test_client_dispersal_time_ms{quantile=\"0.99\"})",
     "legendFormat": "p99"
    },
    {
     "expr": "avg(eigenda_test_client_dispersal_time_ms{quantile=\"0.9\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "avg(eigenda_test_client_dispersal_time_ms{quantile=\"0.5\"})",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Dispersal Rate",
   "type": "timeseries",
   "description": "Rate of blob dispersals per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(eigenda_test_client_dispersal_time_ms_count[$__rate_interval])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(eigenda_test_client_dispersal_time_ms_count[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Validator Reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validator Read Stage Latency",
     "type": "piechart",
     "description": "A breakdown by stage of the time needed to read blobs from the validators.",
     "gridPos": { "h": 16, "w": 16, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(RetrievalClient_GetBlob_stage_latency_ms_sum[5m])) by (stage)\n/\nsum(rate(RetrievalClient_GetBlob_stage_latency_ms_count[5m])) by (stage)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Validator Read Successes / Second",
     "type": "timeseries",
     "description": "Validator read successes per second.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
     "targets": [
      {
       "expr": "increase(eigenda_test_client_validator_read_successes[$__rate_interval]) / $__rate_interval",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(increase(eigenda_test_client_validator_read_successes[$__rate_interval]) / $__rate_interval)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Validator Read Failures / Second",
     "type": "timeseries",
     "description": "Validator read failures / Second",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
     "targets": [
      {
       "expr": "increase(eigenda_test_client_validator_read_failures[$__rate_interval]) / $__rate_interval",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(increase(eigenda_test_client_validator_read_failures[$__rate_interval]) / $__rate_interval)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Validator Reads In Flight",
     "type": "timeseries",
     "description": "Number of validator operations in flight.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eigenda_test_client_operations_in_flight{operation=\"validator_read\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(eigenda_test_client_operations_in_flight{operation=\"validator_read\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Validator Read Latency Percentiles",
     "type": "timeseries",
     "description": "Time required to read from the validators.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(eigenda_test_client_validator_read_time_ms{quantile=\"0.5\"})",
       "legendFormat": "p50"
      },
      {
       "expr": "avg(eigenda_test_client_validator_read_time_ms{quantile=\"0.9\"})",
       "legendFormat": "p90"
      },
      {
       "expr": "avg(eigenda_test_client_validator_read_time_ms{quantile=\"0.99\"})",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Average Validator Read Latency",
     "type": "timeseries",
     "description": "The average time required to read a blob from the validators.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(eigenda_test_client_validator_read_time_ms_sum[$__rate_interval]))\n/\nsum(rate(eigenda_test_client_validator_read_time_ms_count[$__rate_interval]))",
       "legendFormat": "average"
      }
     ]
    },
    {
     "title": "Validator Read Stage Count",
     "type": "timeseries",
     "description": "For all validator reads in flight, the number of blobs in each stage.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum by (stage) (RetrievalClient_GetBlob_stage_count)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Validator Read Rate",
     "type": "timeseries",
     "description": "Rate of blob dispersals per second",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(eigenda_test_client_validator_read_time_ms_count[$__rate_interval]))",
       "legendFormat": "total"
      },
      {
       "expr": "sum by (instance)(rate(eigenda_test_client_validator_read_time_ms_count[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Validator Read Latency By Phase",
     "type": "timeseries",
     "description": "The average latency that the blob spends in various statuses during a read from the validators.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(RetrievalClient_GetBlob_stage_latency_ms_sum[5m])) by (stage)\n/\nsum(rate(RetrievalClient_GetBlob_stage_latency_ms_count[5m])) by (stage)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Relay Reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Relay Reads In Flight",
     "type": "timeseries",
     "description": "Number of relay read operations in flight.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "eigenda_test_client_operations_in_flight{operation=\"relay_read\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(eigenda_test_client_operations_in_flight{operation=\"relay_read\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Reads Per Relay / Second",
     "type": "timeseries",
     "description": "Rate of relay reads per second",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (relay_id) (rate(eigenda_test_client_relay_read_time_ms_count[$__rate_interval]))",
       "legendFormat": "relay {{relay_id}}"
      },
      {
       "expr": "sum(rate(eigenda_test_client_relay_read_time_ms_count[$__rate_interval]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Average Relay Read Latency",
     "type": "timeseries",
     "description": "The average time required to read a blob from the relays.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(eigenda_test_client_relay_read_time_ms_sum[$__rate_interval]) / \nrate(eigenda_test_client_relay_read_time_ms_count[$__rate_interval])",
       "legendFormat": "relay {{relay_id}}"
      }
     ]
    },
    {
     "title": "Succesful Relay Reads / Second",
     "type": "timeseries",
     "description": "Successful relay read operations.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "increase(eigenda_test_client_relay_read_successes[$__rate_interval]) / $__rate_interval",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(increase(eigenda_test_client_relay_read_successes[$__rate_interval]) / $__rate_interval)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Failed Relay Reads / Second",
     "type": "timeseries",
     "description": "Failed relay read operations.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
     "targets": [
      {
       "expr": "increase(eigenda_test_client_relay_read_failures[$__rate_interval]) / $__rate_interval",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(increase(eigenda_test_client_relay_read_failures[$__rate_interval]) / $__rate_interval)",
       "legendFormat": "total"
      }
     ]
    }
   ]
  }
 ]
}