{
 "title": "EigenDA Proxy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "/put requests total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "eigenda_proxy_default_rpc_server_requests_total{method=\"/put/\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "/put requests duration",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eigenda_proxy_default_rpc_server_request_duration_seconds_bucket{method=\"/put/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=\"ops-bedrock-da-server-1\"} |= ``"
    }
   ]
  }
 ]
}