[tools]

# TODO: merge this file with ../../mise.toml after we update ../../go.mod to use go >=1.22
# Core Dependencies
go = "1.22.7"

# Go Dependencies
golangci-lint = "1.64.5"
"go:go.uber.org/mock/mockgen" = "0.5.0"
"go:gotest.tools/gotestsum" = "1.12.0"
"go:github.com/segmentio/golines" = "0.12.0"
