// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: controller/controller_service.proto

package controller

import (
	v2 "github.com/Layr-Labs/eigenda/api/grpc/common/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contains all information necessary for the controller to evaluate the validity of a dispersal payment
type AuthorizePaymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The blob header is used for the following purposes:
	// 1. Contains the PaymentHeader, which describes the payment being offered
	// 2. Contains the quorums being dispersed to
	BlobHeader *v2.BlobHeader `protobuf:"bytes,1,opt,name=blob_header,json=blobHeader,proto3" json:"blob_header,omitempty"`
	// Client's ECDSA signature over the blob header's blobKey (keccak hash of the blob header).
	// This signature can be verified against the account ID in the payment header.
	ClientSignature []byte `protobuf:"bytes,2,opt,name=client_signature,json=clientSignature,proto3" json:"client_signature,omitempty"`
}

func (x *AuthorizePaymentRequest) Reset() {
	*x = AuthorizePaymentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_controller_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePaymentRequest) ProtoMessage() {}

func (x *AuthorizePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePaymentRequest.ProtoReflect.Descriptor instead.
func (*AuthorizePaymentRequest) Descriptor() ([]byte, []int) {
	return file_controller_controller_service_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizePaymentRequest) GetBlobHeader() *v2.BlobHeader {
	if x != nil {
		return x.BlobHeader
	}
	return nil
}

func (x *AuthorizePaymentRequest) GetClientSignature() []byte {
	if x != nil {
		return x.ClientSignature
	}
	return nil
}

// AuthorizePaymentResponse is returned after the controller does accounting and metering.
// - *Accounting* involves checking that there are enough funds/reservation bandwidth available to pay for a dispersal
// - *Metering* involves checking that EigenDA throughput limits are respected, irrespective of client payment validity
//
// A GRPC error indicates that there was a problem with either accounting or metering.
// No error means everything succeeded.
//
// Possible error cases (not an exhaustive list):
// - Unauthenticated: Invalid client signature
// - PermissionDenied: Client signature is valid, but payment is insufficient or account has exceeded reservation limits
// - ResourceExhausted: Metering check failed - total network on-demand throughput is exhausted
type AuthorizePaymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthorizePaymentResponse) Reset() {
	*x = AuthorizePaymentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_controller_controller_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePaymentResponse) ProtoMessage() {}

func (x *AuthorizePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_controller_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePaymentResponse.ProtoReflect.Descriptor instead.
func (*AuthorizePaymentResponse) Descriptor() ([]byte, []int) {
	return file_controller_controller_service_proto_rawDescGZIP(), []int{1}
}

var File_controller_controller_service_proto protoreflect.FileDescriptor

var file_controller_controller_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x1a, 0x19, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x32, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x5f, 0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x17,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x62, 0x5f,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x32, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x0a, 0x62, 0x6c, 0x6f, 0x62, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x29, 0x0a, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x74, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x10, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x61, 0x79, 0x72, 0x2d,
	0x4c, 0x61, 0x62, 0x73, 0x2f, 0x65, 0x69, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_controller_controller_service_proto_rawDescOnce sync.Once
	file_controller_controller_service_proto_rawDescData = file_controller_controller_service_proto_rawDesc
)

func file_controller_controller_service_proto_rawDescGZIP() []byte {
	file_controller_controller_service_proto_rawDescOnce.Do(func() {
		file_controller_controller_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_controller_controller_service_proto_rawDescData)
	})
	return file_controller_controller_service_proto_rawDescData
}

var file_controller_controller_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_controller_controller_service_proto_goTypes = []interface{}{
	(*AuthorizePaymentRequest)(nil),  // 0: controller.AuthorizePaymentRequest
	(*AuthorizePaymentResponse)(nil), // 1: controller.AuthorizePaymentResponse
	(*v2.BlobHeader)(nil),            // 2: common.v2.BlobHeader
}
var file_controller_controller_service_proto_depIdxs = []int32{
	2, // 0: controller.AuthorizePaymentRequest.blob_header:type_name -> common.v2.BlobHeader
	0, // 1: controller.ControllerService.AuthorizePayment:input_type -> controller.AuthorizePaymentRequest
	1, // 2: controller.ControllerService.AuthorizePayment:output_type -> controller.AuthorizePaymentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_controller_controller_service_proto_init() }
func file_controller_controller_service_proto_init() {
	if File_controller_controller_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_controller_controller_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizePaymentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_controller_controller_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizePaymentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_controller_controller_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_controller_service_proto_goTypes,
		DependencyIndexes: file_controller_controller_service_proto_depIdxs,
		MessageInfos:      file_controller_controller_service_proto_msgTypes,
	}.Build()
	File_controller_controller_service_proto = out.File
	file_controller_controller_service_proto_rawDesc = nil
	file_controller_controller_service_proto_goTypes = nil
	file_controller_controller_service_proto_depIdxs = nil
}
