[package]
name = "sov-eigenda-adapter"
version = "0.1.0"
edition = "2024"

[dependencies]
# Sovereign SDK
sov-rollup-interface = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk.git", rev = "508fb90f93f08a7695ddf5ceaddce7841fd31687" }

# EigenDA
eigenda-cert = { git = "ssh://git@github.com/Layr-Labs/hokulea.git", rev = "efe7767dde967008de5309f44fecb72aa2ef1e54" }

# Reth
reth-trie-common = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.6.0", default-features = false, features = [
    "serde",
] }

# Alloy
alloy-consensus = { version = "1.0.23", default-features = false, features = [
    "serde",
    "serde-bincode-compat",
] }
alloy-eips = { version = "1.0.23", default-features = false }
alloy-network = { version = "1.0.23", default-features = false }
alloy-primitives = { version = "1.3.0", default-features = false }
alloy-provider = { version = "1.0.23", default-features = false }
alloy-rlp = { version = "0.3.12", default-features = false }
alloy-rpc-client = { version = "1.0.23", default-features = false }
alloy-rpc-types = { version = "1.0.23", default-features = false }
alloy-rpc-types-eth = { version = "1.0.23", default-features = false }
alloy-signer = { version = "1.0.23", default-features = false }
alloy-signer-local = { version = "1.0.23", default-features = false }
alloy-sol-types = { version = "1.0.23", default-features = false }
alloy-transport = { version = "1.0.23", default-features = false }

# Others
anyhow = { version = "1.0.98", default-features = false }
ark-bn254 = { version = "0.5.0", default-features = false, features = ["curve"] }
ark-ec = { version = "0.5.0", default-features = false }
ark-ff = { version = "0.5.0", default-features = false }
async-trait = "0.1.88"
backon = { version = "1.5.2", optional = true }
bitvec     = { version = "1.0.1", default-features = false }
borsh = { version = "1.5.7", default-features = false, features = ["bytes"] }
bytes = { version = "1.10.1", default-features = false }
derive_more = { version = "2.0.1" }
futures = { version = "0.3.31" }
hashbrown = { version = "0.15.4", default-features = false, features = ["default-hasher"] }
hex = { version = "0.4.3" }
reqwest = { version = "0.12.22", features = ["json"], optional = true }
 # Pinned so that it's same as https://github.com/Sovereign-Labs/sovereign-sdk/blob/508fb90f93f08a7695ddf5ceaddce7841fd31687/Cargo.toml#L250
schemars = { version = "0.8.21", default-features = false, features = [ "derive", ] }
serde = { version = "1.0.219", default-features = false, features = [ "alloc", "derive", ] }
serde_json = { version = "1.0.141" }
serde_with = { version = "3.14.0" }
thiserror  = { version = "2.0.12", default-features = false }
tiny-keccak  = { version = "2.0.2", default-features = false, features = ["keccak"] }
tokio = { version = "1.47.1", features = ["sync"], optional = true }
tracing = { version = "0.1.41" }
url = { version = "2.5.4" }

[dev-dependencies]
alloy-provider = { version = "1.0.23", default-features = false, features = [
    "anvil-api",
] }
alloy-rpc-types = { version = "1.0.23", default-features = false, features = [
    "anvil",
] }
hex = "0.4.3"
# Pinned so that it's same as https://github.com/Sovereign-Labs/sovereign-sdk/blob/508fb90f93f08a7695ddf5ceaddce7841fd31687/Cargo.toml#L261
risc0-zkvm = { version = "2.1", default-features = false, features = ["std"] }
testcontainers = "0.25.0"

[features]
default = []
native = [
    # Sovereign SDK
    "sov-rollup-interface/native",
    # Alloy
    "alloy-rpc-types/anvil",
    "alloy-provider/anvil-api",
    "alloy-provider/ws",
    "alloy-provider/reqwest",
    "alloy-eips/kzg",
    # Reth
    "reth-trie-common/eip1186",
    # Others
    "dep:backon",
    "dep:tokio",
    "dep:reqwest",
]
