[package]
name = "sov-eigenda-adapter"
version = "0.1.0"
edition = "2024"

[dependencies]
sov-rollup-interface = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "a25b7634c3a0eaa40acf57503508956a74291cdd" }

anyhow = { version = "1.0.98", default-features = false }
async-trait = "0.1.88"
borsh = { version = "1.5.7", default-features = false, features = ["bytes"] }
schemars = { version = "0.8.22", default-features = false, features = [
    "derive",
] }
thiserror = "2.0.12"
serde = { version = "1.0.219", default-features = false, features = [
    "alloc",
    "derive",
] }
tokio = { version = "1.45.1", features = ["sync"], optional = true }

[dev-dependencies]

[features]
default = []
native = ["dep:tokio", "sov-rollup-interface/native"]
