[package]
name = "sov-eigenda-adapter"
version = "0.1.0"
edition = "2024"

[dependencies]
# Sovereign SDK
sov-rollup-interface = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk.git", rev = "464eedff20ed53fe96bc8d5befef5fddbe16b063" }

# Reth
reth-trie-common = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.4", default-features = false, features = [
    "serde",
] }

# Alloy
#
# NOTE: Alloy dependencies are pinned to compatible versions to resolve c-kzg
# native library conflicts. The conflict happens because `sovereign-sdk` is
# using an older revm version that is still using the `c-kzg.version = 1`
alloy-primitives = { version = "0.8.25", default-features = false }
alloy-rlp = { version = "0.3.12", default-features = false }
alloy-sol-types = { version = "0.8.25", default-features = false }
alloy-trie = { version = "0.9.1" }

alloy-eips = { version = "0.12.6", default-features = false }
alloy-network = { version = "0.12.6", default-features = false }
alloy-provider = { version = "0.12.6", default-features = false }
alloy-rpc-client = { version = "0.12.6", default-features = false }
alloy-rpc-types = { version = "0.12.6", default-features = false }
alloy-rpc-types-eth = { version = "0.12.6", default-features = false }
alloy-signer = { version = "0.12.6", default-features = false }
alloy-signer-local = { version = "0.12.6", default-features = false }
alloy-transport = { version = "0.12.6", default-features = false }
alloy-consensus = { version = "0.12.6", default-features = false, features = [
    "serde",
    "serde-bincode-compat",
    "k256",
] }

# Others
anyhow = { version = "1.0.98", default-features = false }
ark-bn254 = { version = "0.5.0", default-features = false, features = [
    "curve",
] }
ark-ec = { version = "0.5.0", default-features = false }
ark-ff = { version = "0.5.0", default-features = false }
ark-serialize = { version = "0.5.0", default-features = false, features = [
    "derive",
] }
async-trait = "0.1.88"
backon = { version = "1.5.2", optional = true }
bitvec = { version = "1.0.1", default-features = false }
borsh = { version = "1.5.7", default-features = false, features = ["bytes"] }
bytes = { version = "1.10.1", default-features = false }
derive_more = { version = "2.0.1" }
futures = { version = "0.3.31" }
hashbrown = { version = "0.15.4", default-features = false, features = [
    "default-hasher",
] }
hex = { version = "0.4.3" }
reqwest = { version = "0.12.22", features = ["json"], optional = true }
rustls = { version = "0.23.31", features = ["aws-lc-rs"], optional = true }
rust-kzg-bn254-primitives = { version = "0.1.2", default-features = false }
rust-kzg-bn254-prover = { version = "0.1.1", default-features = false }
# Pinned so that it's same as https://github.com/Sovereign-Labs/sovereign-sdk/blob/464eedff20ed53fe96bc8d5befef5fddbe16b063/Cargo.toml#L246
schemars = { version = "0.8.21", default-features = false, features = [
    "derive",
] }
serde = { version = "1.0.219", default-features = false, features = [
    "alloc",
    "derive",
] }
serde_json = { version = "1.0.141" }
serde_with = { version = "3.14.0" }
thiserror = { version = "2.0.12", default-features = false }
tiny-keccak = { version = "2.0.2", default-features = false, features = [
    "keccak",
] }
tokio = { version = "1.47.1", features = ["sync"], optional = true }
tracing = { version = "0.1.41" }
url = { version = "2.5.4" }
arbitrary = { version = "1.3", optional = true }
proptest = { version = "1.7.0", features = ["alloc", "std"], optional = true }

[build-dependencies]
ark-bn254 = { version = "0.5.0", default-features = false }
ark-serialize = { version = "0.5.0", default-features = false, features = [
    "derive",
] }
bincode = { version = "2.0.1", default-features = false, features = ["derive"] }
rust-kzg-bn254-prover = { version = "0.1.1", default-features = false }

[dev-dependencies]
bincode = { version = "2.0.1", default-features = false, features = [
    "derive",
    "serde",
    "std",
] }
rand = { version = "0.8" }
alloy-provider = { version = "0.12.6", default-features = false, features = [
    "anvil-api",
] }
alloy-rpc-types = { version = "0.12.6", default-features = false, features = [
    "anvil",
] }
alloy-consensus = { version = "0.12.6", default-features = false, features = [
    "arbitrary",
] }
hex = "0.4.3"
# Pinned so that it's same as https://github.com/Sovereign-Labs/sovereign-sdk/blob/464eedff20ed53fe96bc8d5befef5fddbe16b063/Cargo.toml#L257
risc0-zkvm = { version = "2.1", default-features = false, features = ["std"] }
testcontainers = "0.25.0"

[features]
default = []
arbitrary = ["dep:arbitrary", "dep:proptest"]
native = [
    # Sovereign SDK
    "sov-rollup-interface/native",
    # Alloy
    "alloy-rpc-types/anvil",
    "alloy-rpc-client/default",
    "alloy-rpc-client/ws",
    "alloy-provider/anvil-api",
    "alloy-provider/default",
    "alloy-provider/ws",
    "alloy-eips/kzg",
    # Reth
    "reth-trie-common/eip1186",
    # Others
    "dep:rustls",
    "dep:backon",
    "dep:tokio",
    "dep:reqwest",
]
