[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./" }]

remappings = [
    "@eigenlayer-middleware/=lib/eigenlayer-middleware/src/",
    "@eigenlayer-core/=lib/eigenlayer-contracts/src/",
    "@eigenlayer-scripts/=lib/eigenlayer-contracts/script/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=lib/openzeppelin-contracts-upgradeable/",
    "forge-std/=lib/forge-std/src/",
]

gas_reports = ["*"]

# A list of ignored solc error codes

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = false
# Override the Solidity version (this overrides `auto_detect_solc`)
solc_version = '0.8.12'
