[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./" }]

# We force all warnings to be fixed
deny_warnings = true
# We error warnings from libraries. This should be fixed upstream but I'm lazy.
# See https://github.com/ethereum/solidity/issues/2675 for an interesting discussion.
ignored_warnings_from = [
    "lib/eigenlayer-middleware/src/RegistryCoordinator.sol",
]

gas_reports = ["*"]

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = false
# Override the Solidity version (this overrides `auto_detect_solc`)
solc_version = '0.8.12'
