### CORE ###

# Only this address can finalize the deployment and be the owner of the deployed contracts.
# Currently just set to the deployer. The deployer will have to transfer ownership of each contract to an ops multisig when it is created.
initialOwner = "0xDF291ebfe90eF9187c3f45609603E366a21a16Ea"

# Parameters shared across various deployed contracts
[initParams.shared]
rewardsCoordinator = "0x5ae8152fb88c26ff9ca5C014c94fca3c68029349"
avsDirectory = "0xa789c91ECDdae96865913130B786140Ee17aF545"
delegationManager = "0xD4A7E1Bd8015057293f0D0A557088c286942e84b"
initialPausedStatus = 0

# Parameters for the pauser registry contract
[initParams.core.pauserRegistry]
pausers = [] # Settable by unpauser
unpauser = "0xDF291ebfe90eF9187c3f45609603E366a21a16Ea" # Settable by unpauser

### MIDDLEWARE ###

# Parameters for the registry coordinator contract
[initParams.middleware.registryCoordinator]
churnApprover = "0x8Fc54A397586a5948cb4700B59397f2Ce0903Fd1" # Settable by owner
# The following can be added by owner through createQuorum()
minimumStakes = []
strategyParams = []
operatorSetParams = []

# Parameters for the ejection manager contract
[initParams.middleware.ejectionManager]
ejectors = [] # Settable by owner
quorumEjectionParams = [] # Settable by owner

### EIGEN DA ###

# Parameters for the Threshold Registry contract
[initParams.eigenDA.thresholdRegistry]
# To be updated in a contract upgrade since they are immutable.
quorumAdversaryThresholdPercentages = "0x" 
quorumConfirmationThresholdPercentages = "0x" 
quorumNumbersRequired = "0x" 
# Can be added by owner
versionedBlobParams = [] 

# Parameters for the payment vault contract
[initParams.eigenDA.paymentVault]
minNumSymbols = 4096
pricePerSymbol = 447000000
priceUpdateCooldown = 1
globalSymbolsPerPeriod = 131072
reservationPeriodInterval = 300
globalRatePeriodInterval = 30

# Parameters for the rewards initiator contract
[initParams.eigenDA.serviceManager]
rewardsInitiator = "0xDA29BB71669f46F2a779b4b62f03644A84eE3479" # Settable by owner
batchConfirmers = [] # Can be added by owner
