[profile.default]
src = 'RegistryCoordinator/src'
out = 'out'
libs = ['lib']

# Compilation settings from Etherscan
solc_version = '0.8.12'
optimizer = true
optimizer_runs = 200
evm_version = 'london'

# Basic remappings for src/ structure
remappings = [
  "@openzeppelin-upgrades/=RegistryCoordinator/lib/openzeppelin-contracts-upgradeable/",
  "@openzeppelin/=RegistryCoordinator/lib/openzeppelin-contracts/",
  "eigenlayer-contracts/=RegistryCoordinator/lib/eigenlayer-contracts/"
]
