name: compile-protobufs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  golangci:
    name: Compile Protobufs
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.3
        with:
          egress-policy: audit
      - name: Checkout EigenDA
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
      - name: Recompile Protobufs
        run: |
          make clean
          make protoc
      - name: Verify No Git Changes
        run: ./api/builder/is-repo-clean.sh
