name: compile-protobufs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: ''

jobs:
  golangci:
    name: Compile Protobufs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            auth.docker.io:443
            deb.debian.org:80
            github.com:443
            objects.githubusercontent.com:443
            production.cloudflare.docker.com:443
            proxy.golang.org:443
            registry-1.docker.io:443
            sum.golang.org:443
      - name: Checkout EigenDA
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
      - name: Recompile Protobufs
        run: |
          make clean
          make protoc
      - name: Verify No Git Changes
        run: ./api/builder/is-repo-clean.sh
