name: fuzz-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  go-test:
    outputs:
      COVERAGE: ${{ steps.unit.outputs.coverage }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install project dependencies
      run: | 
        go mod download

    - name: Run E2E Fuzz Tests
      run: | 
        make e2e-fuzz-test
