# From https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Actions
name: Publish Spec MdBook
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install mdbook and mdbook plugins
        run: |
          cargo install mdbook
          cargo install mdbook-mermaid
      - name: Build Book
        run: mdbook build
        working-directory: docs/spec
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/spec/book'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4