name: Push Proxy Release Image to ghcr # This name is displayed in the badge

on:
  push:
    branches:
      - 'master'
    tags:
      - 'proxy/v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eigenda-proxy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log into the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api/proxy
          push: true
          # TODO: this might not work after we moved this action to the monorepo...
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}